(define (problem mprime-x-26)
	(:domain mystery-prime-typed)
	(:objects
		pepper papaya flounder endive marzipan haroset turkey scallop pistachio snickers hamburger rice - food
		understanding learning entertainment empathy satisfaction - pleasure
		depression boils hangover jealousy - pain
	)
	(:init
		(eats scallop hamburger)
		(eats rice haroset)
		(eats endive pistachio)
		(= (locale turkey) 4.0)
		(= (locale scallop) 4.0)
		(eats scallop rice)
		(eats haroset marzipan)
		(= (locale marzipan) 0.0)
		(eats hamburger marzipan)
		(craves satisfaction snickers)
		(= (harmony empathy) 2.0)
		(craves understanding papaya)
		(eats papaya turkey)
		(= (locale haroset) 5.0)
		(eats papaya flounder)
		(= (locale hamburger) 5.0)
		(eats snickers hamburger)
		(= (locale endive) 1.0)
		(eats haroset endive)
		(eats marzipan hamburger)
		(craves empathy scallop)
		(eats snickers pepper)
		(= (locale rice) 4.0)
		(= (harmony understanding) 1.0)
		(craves hangover pistachio)
		(eats hamburger haroset)
		(eats marzipan turkey)
		(eats turkey papaya)
		(eats marzipan haroset)
		(craves entertainment haroset)
	)
	(:goal
			(and
				(craves boils papaya)
			)
	)
)