(define (problem mprime-x-26)
	(:domain mystery-prime-typed)
	(:objects
		pepper papaya flounder endive marzipan haroset turkey scallop pistachio snickers hamburger rice - food
		understanding learning entertainment empathy satisfaction - pleasure
		depression boils hangover jealousy - pain
	)
	(:init
		(= (harmony understanding) 1.0)
		(eats endive pistachio)
		(eats pistachio turkey)
		(eats papaya turkey)
		(craves satisfaction snickers)
		(eats turkey pistachio)
		(craves understanding papaya)
		(eats haroset hamburger)
		(eats rice pistachio)
		(eats endive haroset)
		(eats marzipan haroset)
		(eats rice haroset)
		(eats pistachio endive)
		(eats hamburger marzipan)
		(= (locale rice) 4.0)
		(craves empathy scallop)
		(= (harmony learning) 1.0)
		(= (locale pepper) 0.0)
		(= (harmony entertainment) 1.0)
		(eats snickers pepper)
		(eats hamburger scallop)
		(= (locale haroset) 5.0)
		(craves jealousy snickers)
		(eats hamburger haroset)
		(= (locale flounder) 2.0)
		(eats papaya flounder)
		(eats turkey marzipan)
		(eats snickers hamburger)
		(craves boils haroset)
		(eats endive rice)
		(eats rice endive)
		(eats haroset marzipan)
		(= (locale endive) 1.0)
		(eats rice scallop)
		(= (harmony satisfaction) 3.0)
		(eats flounder papaya)
		(craves depression marzipan)
		(= (harmony empathy) 2.0)
		(eats pepper snickers)
		(eats flounder pepper)
		(= (locale pistachio) 1.0)
		(craves entertainment haroset)
		(= (locale papaya) 1.0)
		(= (locale snickers) 1.0)
		(eats marzipan hamburger)
		(eats haroset endive)
		(eats turkey papaya)
		(eats pepper flounder)
		(= (locale hamburger) 5.0)
		(= (locale turkey) 4.0)
		(eats haroset rice)
		(craves hangover pistachio)
		(eats marzipan turkey)
		(craves learning marzipan)
		(= (locale scallop) 4.0)
		(= (locale marzipan) 0.0)
		(eats scallop hamburger)
		(eats pistachio rice)
		(eats scallop rice)
		(eats hamburger snickers)
	)
	(:goal
			(and
				(craves boils papaya)
			)
	)
)