(define (problem mprime-x-26)
	(:domain mystery-prime-typed)
	(:objects
		pepper papaya flounder endive marzipan haroset turkey scallop pistachio snickers hamburger rice - food
		understanding learning entertainment empathy satisfaction - pleasure
		depression boils hangover jealousy - pain
	)
	(:init
		(craves satisfaction snickers)
		(eats hamburger scallop)
		(eats hamburger snickers)
		(eats haroset endive)
		(= (locale papaya) 1.0)
		(eats pistachio turkey)
		(eats snickers hamburger)
		(= (harmony learning) 1.0)
		(eats haroset hamburger)
		(eats haroset rice)
		(eats flounder papaya)
		(eats hamburger haroset)
		(eats scallop rice)
		(eats pistachio endive)
		(eats marzipan hamburger)
		(= (harmony entertainment) 1.0)
		(eats turkey marzipan)
		(craves empathy scallop)
		(craves hangover pistachio)
		(craves depression marzipan)
		(eats hamburger marzipan)
		(craves understanding papaya)
		(eats rice endive)
		(craves jealousy snickers)
		(= (harmony empathy) 2.0)
		(= (harmony satisfaction) 3.0)
		(= (locale haroset) 5.0)
		(= (locale pepper) 0.0)
		(= (harmony understanding) 1.0)
		(eats scallop hamburger)
		(craves boils haroset)
		(eats flounder pepper)
		(eats endive haroset)
		(eats pepper flounder)
		(= (locale rice) 4.0)
		(= (locale hamburger) 5.0)
		(eats rice haroset)
		(eats haroset marzipan)
		(eats papaya flounder)
		(eats snickers pepper)
		(= (locale endive) 1.0)
		(= (locale flounder) 2.0)
		(= (locale scallop) 4.0)
		(craves learning marzipan)
		(= (locale marzipan) 0.0)
	)
	(:goal
			(and
				(craves boils papaya)
			)
	)
)