(define (problem roverprob1423)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 rover2 rover3 - rover
		rover0store rover1store rover2store rover3store - store
		waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 - waypoint
		camera0 camera1 camera2 camera3 - camera
		objective0 objective1 objective2 - objective
	)
	(:init
		(visible waypoint4 waypoint2)
		(visible waypoint4 waypoint1)
		(on_board camera1 rover3)
		(can_traverse rover0 waypoint1 waypoint0)
		(can_traverse rover0 waypoint2 waypoint0)
		(in_sun waypoint0)
		(visible waypoint0 waypoint2)
		(visible waypoint2 waypoint3)
		(can_traverse rover2 waypoint0 waypoint3)
		(empty rover1store)
		(equipped_for_soil_analysis rover0)
		(can_traverse rover3 waypoint5 waypoint2)
		(at_rock_sample waypoint3)
		(empty rover0store)
		(can_traverse rover0 waypoint0 waypoint2)
		(equipped_for_rock_analysis rover3)
		(visible_from objective2 waypoint2)
		(can_traverse rover0 waypoint3 waypoint2)
		(visible waypoint4 waypoint5)
		(can_traverse rover2 waypoint2 waypoint4)
		(= (energy rover0) 50.0)
		(can_traverse rover1 waypoint2 waypoint5)
		(can_traverse rover1 waypoint0 waypoint1)
		(supports camera3 low_res)
		(can_traverse rover3 waypoint2 waypoint3)
		(visible_from objective0 waypoint2)
		(can_traverse rover2 waypoint2 waypoint1)
		(equipped_for_imaging rover1)
		(calibration_target camera2 objective0)
		(visible waypoint0 waypoint4)
		(can_traverse rover3 waypoint1 waypoint0)
		(supports camera0 low_res)
		(on_board camera2 rover1)
		(at_soil_sample waypoint4)
		(calibration_target camera1 objective0)
		(visible waypoint3 waypoint4)
		(in rover0 waypoint2)
		(supports camera1 colour)
		(in_sun waypoint3)
		(visible waypoint5 waypoint1)
		(calibration_target camera0 objective1)
		(at_rock_sample waypoint4)
		(can_traverse rover1 waypoint0 waypoint2)
		(visible waypoint1 waypoint4)
		(equipped_for_imaging rover2)
		(in_sun waypoint4)
		(can_traverse rover2 waypoint5 waypoint2)
		(visible waypoint4 waypoint3)
		(store_of rover2store rover2)
		(at_rock_sample waypoint5)
		(empty rover2store)
		(can_traverse rover2 waypoint0 waypoint2)
		(visible_from objective2 waypoint1)
		(can_traverse rover1 waypoint4 waypoint3)
		(can_traverse rover3 waypoint2 waypoint5)
		(can_traverse rover3 waypoint4 waypoint3)
		(can_traverse rover1 waypoint1 waypoint0)
		(visible_from objective0 waypoint1)
		(visible_from objective1 waypoint0)
		(can_traverse rover2 waypoint3 waypoint0)
		(can_traverse rover0 waypoint0 waypoint1)
		(can_traverse rover0 waypoint5 waypoint3)
		(can_traverse rover0 waypoint2 waypoint3)
		(visible_from objective0 waypoint0)
		(can_traverse rover1 waypoint5 waypoint2)
		(visible waypoint1 waypoint5)
		(visible waypoint2 waypoint4)
		(visible waypoint1 waypoint2)
		(can_traverse rover1 waypoint3 waypoint2)
		(in rover3 waypoint3)
		(visible waypoint3 waypoint2)
		(= (recharges) 0.0)
		(can_traverse rover1 waypoint2 waypoint3)
		(at_soil_sample waypoint1)
		(can_traverse rover1 waypoint3 waypoint4)
		(visible waypoint3 waypoint5)
		(visible waypoint5 waypoint3)
		(can_traverse rover1 waypoint2 waypoint0)
		(can_traverse rover0 waypoint4 waypoint2)
		(can_traverse rover3 waypoint0 waypoint1)
		(equipped_for_rock_analysis rover1)
		(on_board camera3 rover2)
		(equipped_for_rock_analysis rover0)
		(visible waypoint2 waypoint0)
		(visible waypoint5 waypoint2)
		(calibration_target camera3 objective1)
		(= (energy rover3) 50.0)
		(supports camera2 low_res)
		(= (energy rover1) 50.0)
		(available rover0)
		(can_traverse rover3 waypoint3 waypoint0)
		(supports camera3 colour)
		(visible waypoint2 waypoint1)
		(visible waypoint3 waypoint0)
		(visible_from objective2 waypoint0)
		(available rover2)
		(visible waypoint1 waypoint0)
		(supports camera0 colour)
		(can_traverse rover2 waypoint1 waypoint2)
	)
	(:goal
			(and
				(communicated_soil_data waypoint1)
				(communicated_soil_data waypoint3)
				(communicated_soil_data waypoint4)
				(communicated_rock_data waypoint5)
				(communicated_rock_data waypoint4)
				(communicated_image_data objective0 low_res)
				(communicated_image_data objective0 high_res)
				(communicated_image_data objective2 low_res)
			)
	)
)