(define (problem roverprob4123)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 rover2 - rover
		rover0store rover1store rover2store - store
		waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 - waypoint
		camera0 camera1 - camera
		objective0 objective1 - objective
	)
	(:init
		(visible waypoint0 waypoint2)
		(visible waypoint1 waypoint5)
		(can_traverse rover1 waypoint1 waypoint0)
		(can_traverse rover1 waypoint3 waypoint0)
		(visible waypoint3 waypoint4)
		(visible waypoint0 waypoint1)
		(supports camera1 high_res)
		(visible_from objective1 waypoint3)
		(visible waypoint2 waypoint5)
		(can_traverse rover0 waypoint2 waypoint5)
		(on_board camera1 rover2)
		(= (recharges) 0.0)
		(on_board camera0 rover0)
		(can_traverse rover1 waypoint3 waypoint4)
		(at_rock_sample waypoint2)
		(can_traverse rover2 waypoint0 waypoint3)
		(can_traverse rover2 waypoint2 waypoint5)
		(can_traverse rover0 waypoint2 waypoint3)
		(supports camera0 high_res)
		(visible waypoint5 waypoint2)
		(visible_from objective1 waypoint2)
		(visible_from objective0 waypoint0)
		(store_of rover0store rover0)
		(visible waypoint4 waypoint0)
		(in rover2 waypoint4)
		(in rover1 waypoint3)
		(equipped_for_soil_analysis rover0)
		(visible waypoint0 waypoint3)
		(can_traverse rover2 waypoint4 waypoint0)
		(can_traverse rover0 waypoint5 waypoint2)
		(visible_from objective0 waypoint1)
		(store_of rover2store rover2)
		(visible_from objective0 waypoint4)
		(visible waypoint4 waypoint3)
		(store_of rover1store rover1)
		(calibration_target camera1 objective1)
		(visible waypoint1 waypoint2)
		(visible waypoint3 waypoint0)
		(can_traverse rover0 waypoint0 waypoint4)
		(visible_from objective1 waypoint0)
		(can_traverse rover0 waypoint1 waypoint2)
		(can_traverse rover1 waypoint2 waypoint3)
		(at_rock_sample waypoint4)
		(visible_from objective0 waypoint3)
		(can_traverse rover2 waypoint1 waypoint0)
		(supports camera0 colour)
		(= (energy rover0) 50.0)
		(equipped_for_rock_analysis rover1)
		(visible waypoint2 waypoint0)
		(channel_free general)
		(can_traverse rover1 waypoint3 waypoint2)
		(empty rover2store)
		(can_traverse rover0 waypoint4 waypoint0)
		(= (energy rover1) 50.0)
		(empty rover1store)
		(visible waypoint5 waypoint0)
		(visible_from objective1 waypoint1)
		(available rover0)
		(visible waypoint4 waypoint5)
		(can_traverse rover1 waypoint0 waypoint5)
		(visible waypoint0 waypoint4)
		(at_lander general waypoint3)
		(equipped_for_soil_analysis rover2)
		(in rover0 waypoint2)
		(at_rock_sample waypoint5)
		(equipped_for_rock_analysis rover0)
		(available rover2)
		(empty rover0store)
		(can_traverse rover0 waypoint2 waypoint1)
		(calibration_target camera0 objective0)
		(at_soil_sample waypoint4)
		(visible waypoint1 waypoint0)
		(visible waypoint2 waypoint3)
		(can_traverse rover1 waypoint4 waypoint3)
		(available rover1)
	)
	(:goal
			(and
				(communicated_soil_data waypoint4)
				(communicated_soil_data waypoint1)
				(communicated_rock_data waypoint3)
				(communicated_rock_data waypoint2)
				(communicated_rock_data waypoint4)
				(communicated_image_data objective0 high_res)
			)
	)
)