(define (problem roverprob4132)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 rover2 rover3 - rover
		rover0store rover1store rover2store rover3store - store
		waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 - waypoint
		camera0 camera1 camera2 camera3 camera4 - camera
		objective0 objective1 objective2 - objective
	)
	(:init
		(can_traverse rover0 waypoint6 waypoint5)
		(visible waypoint0 waypoint1)
		(at_soil_sample waypoint0)
		(can_traverse rover3 waypoint1 waypoint4)
		(can_traverse rover0 waypoint5 waypoint1)
		(can_traverse rover2 waypoint3 waypoint0)
		(on_board camera4 rover1)
		(at_soil_sample waypoint6)
		(can_traverse rover1 waypoint2 waypoint5)
		(= (recharges) 0.0)
		(can_traverse rover1 waypoint2 waypoint1)
		(store_of rover1store rover1)
		(supports camera4 low_res)
		(empty rover0store)
		(visible waypoint6 waypoint0)
		(supports camera2 low_res)
		(visible_from objective0 waypoint0)
		(can_traverse rover1 waypoint0 waypoint2)
		(on_board camera0 rover3)
		(at_soil_sample waypoint5)
		(can_traverse rover2 waypoint1 waypoint0)
		(available rover0)
		(can_traverse rover2 waypoint0 waypoint1)
		(empty rover1store)
		(visible waypoint1 waypoint3)
		(visible waypoint0 waypoint6)
		(can_traverse rover0 waypoint0 waypoint5)
		(on_board camera2 rover0)
		(can_traverse rover1 waypoint6 waypoint2)
		(supports camera3 colour)
		(can_traverse rover1 waypoint4 waypoint1)
		(visible waypoint5 waypoint0)
		(visible waypoint1 waypoint6)
		(can_traverse rover0 waypoint1 waypoint4)
		(visible_from objective2 waypoint4)
		(visible waypoint0 waypoint3)
		(visible waypoint6 waypoint3)
		(visible waypoint4 waypoint1)
		(visible waypoint3 waypoint6)
		(can_traverse rover0 waypoint5 waypoint0)
		(can_traverse rover1 waypoint1 waypoint4)
		(can_traverse rover0 waypoint5 waypoint6)
		(can_traverse rover0 waypoint4 waypoint1)
		(at_rock_sample waypoint5)
		(supports camera3 low_res)
		(supports camera0 colour)
		(at_rock_sample waypoint0)
		(calibration_target camera1 objective2)
		(visible_from objective2 waypoint0)
		(can_traverse rover2 waypoint0 waypoint6)
		(in rover3 waypoint2)
		(visible waypoint3 waypoint1)
		(at_soil_sample waypoint4)
		(visible_from objective2 waypoint6)
		(visible waypoint3 waypoint4)
		(visible_from objective1 waypoint5)
		(empty rover2store)
		(in rover0 waypoint5)
		(visible_from objective2 waypoint2)
		(equipped_for_imaging rover2)
		(can_traverse rover1 waypoint3 waypoint1)
		(on_board camera3 rover2)
		(visible_from objective1 waypoint3)
		(visible waypoint0 waypoint5)
		(can_traverse rover3 waypoint4 waypoint1)
		(equipped_for_soil_analysis rover2)
		(visible_from objective1 waypoint1)
		(calibration_target camera0 objective2)
		(can_traverse rover1 waypoint5 waypoint2)
		(equipped_for_rock_analysis rover1)
		(in rover1 waypoint2)
		(at_soil_sample waypoint1)
		(visible waypoint6 waypoint5)
		(on_board camera1 rover0)
		(available rover3)
		(can_traverse rover2 waypoint6 waypoint0)
		(= (energy rover2) 50.0)
		(can_traverse rover2 waypoint5 waypoint1)
	)
	(:goal
			(and
				(communicated_soil_data waypoint6)
				(communicated_soil_data waypoint4)
				(communicated_soil_data waypoint0)
				(communicated_rock_data waypoint6)
				(communicated_rock_data waypoint0)
				(communicated_rock_data waypoint3)
				(communicated_image_data objective2 low_res)
				(communicated_image_data objective2 colour)
			)
	)
)