(define (problem roverprob4132)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 rover2 rover3 - rover
		rover0store rover1store rover2store rover3store - store
		waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 - waypoint
		camera0 camera1 camera2 camera3 camera4 - camera
		objective0 objective1 objective2 - objective
	)
	(:init
		(empty rover2store)
		(can_traverse rover2 waypoint0 waypoint1)
		(visible_from objective2 waypoint6)
		(can_traverse rover3 waypoint3 waypoint0)
		(equipped_for_rock_analysis rover1)
		(can_traverse rover2 waypoint1 waypoint0)
		(visible waypoint6 waypoint3)
		(visible waypoint0 waypoint1)
		(supports camera1 colour)
		(supports camera3 low_res)
		(visible_from objective1 waypoint5)
		(store_of rover2store rover2)
		(can_traverse rover1 waypoint3 waypoint1)
		(can_traverse rover2 waypoint1 waypoint5)
		(in rover0 waypoint5)
		(can_traverse rover2 waypoint3 waypoint4)
		(visible waypoint4 waypoint3)
		(visible waypoint3 waypoint6)
		(can_traverse rover1 waypoint1 waypoint2)
		(visible_from objective0 waypoint0)
		(calibration_target camera0 objective2)
		(store_of rover0store rover0)
		(supports camera4 colour)
		(visible waypoint3 waypoint1)
		(channel_free general)
		(at_soil_sample waypoint5)
		(visible waypoint4 waypoint1)
		(can_traverse rover0 waypoint5 waypoint0)
		(in rover1 waypoint2)
		(can_traverse rover3 waypoint5 waypoint0)
		(can_traverse rover2 waypoint4 waypoint3)
		(visible_from objective1 waypoint1)
		(visible waypoint3 waypoint4)
		(= (energy rover2) 50.0)
		(at_rock_sample waypoint5)
		(on_board camera3 rover2)
		(can_traverse rover3 waypoint1 waypoint4)
		(can_traverse rover3 waypoint2 waypoint6)
		(empty rover3store)
	)
	(:goal
			(and
				(communicated_soil_data waypoint6)
				(communicated_soil_data waypoint4)
				(communicated_soil_data waypoint0)
				(communicated_rock_data waypoint6)
				(communicated_rock_data waypoint0)
				(communicated_rock_data waypoint3)
				(communicated_image_data objective2 low_res)
				(communicated_image_data objective2 colour)
			)
	)
)