(define (problem delivery-x-7)
	(:domain delivery)
	(:objects
		rooma roomb roomc roomd - room
		item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(= (current_load bot1) 0.0)
		(= (weight item10) 1.0)
		(= (weight item1) 2.0)
		(at item6 rooma)
		(door roomb rooma)
		(door roomd roomc)
		(mount right2 bot2)
		(at item15 rooma)
		(door rooma roomc)
		(= (weight item6) 1.0)
		(door roomc rooma)
		(door roomc roomd)
		(free left2)
		(= (weight item16) 3.0)
		(at-bot bot2 rooma)
		(free right2)
		(= (weight item12) 2.0)
		(= (weight item11) 2.0)
		(at item7 rooma)
		(= (weight item15) 3.0)
		(at item8 rooma)
		(= (weight item9) 1.0)
		(at item10 rooma)
		(= (weight item3) 1.0)
		(= (load_limit bot2) 6.0)
		(mount left2 bot2)
		(= (weight item4) 1.0)
		(mount right1 bot1)
		(free right1)
		(free left1)
		(= (weight item5) 1.0)
		(= (weight item8) 1.0)
		(= (cost) 0.0)
		(at item4 rooma)
		(at item11 rooma)
		(at item3 rooma)
		(at item16 rooma)
		(= (load_limit bot1) 6.0)
		(door rooma roomb)
		(at item13 rooma)
		(= (weight item13) 3.0)
	)
	(:goal
			(and
				(at item16 roomd)
				(at item15 roomd)
				(at item14 roomd)
				(at item13 roomd)
				(at item12 roomb)
				(at item11 roomb)
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomb)
				(at item7 roomb)
				(at item6 roomc)
				(at item5 roomc)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)