(define (problem delivery-x-7)
	(:domain delivery)
	(:objects
		rooma roomb roomc roomd - room
		item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(= (current_load bot2) 0.0)
		(at item2 rooma)
		(door roomb roomd)
		(door roomc roomd)
		(door roomb rooma)
		(= (load_limit bot1) 6.0)
		(= (weight item7) 1.0)
		(door roomc rooma)
		(at-bot bot1 rooma)
		(free left1)
		(at item16 rooma)
		(door rooma roomb)
		(free right2)
		(= (weight item10) 1.0)
		(at item6 rooma)
		(= (weight item15) 3.0)
		(at item1 rooma)
		(at item11 rooma)
		(= (load_limit bot2) 6.0)
		(= (weight item4) 1.0)
		(mount right1 bot1)
		(= (weight item6) 1.0)
		(= (current_load bot1) 0.0)
		(at item13 rooma)
		(at item7 rooma)
		(mount left1 bot1)
		(at item9 rooma)
	)
	(:goal
			(and
				(at item16 roomd)
				(at item15 roomd)
				(at item14 roomd)
				(at item13 roomd)
				(at item12 roomb)
				(at item11 roomb)
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomb)
				(at item7 roomb)
				(at item6 roomc)
				(at item5 roomc)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)