(define (problem delivery-x-7)
	(:domain delivery)
	(:objects
		rooma roomb roomc roomd - room
		item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(= (current_load bot1) 0.0)
		(free right2)
		(= (weight item10) 1.0)
		(at item13 rooma)
		(at item11 rooma)
		(door rooma roomc)
		(= (current_load bot2) 0.0)
		(= (cost) 0.0)
		(free left2)
		(at item2 rooma)
		(at item10 rooma)
		(door roomc rooma)
		(free right1)
		(= (load_limit bot2) 6.0)
		(at item1 rooma)
		(= (weight item7) 1.0)
		(at item15 rooma)
		(mount right2 bot2)
		(at item3 rooma)
		(= (weight item1) 2.0)
		(= (weight item14) 3.0)
		(at item6 rooma)
		(= (weight item16) 3.0)
		(mount right1 bot1)
		(at item4 rooma)
		(= (weight item15) 3.0)
		(at-bot bot2 rooma)
		(door roomd roomc)
		(free left1)
		(at item14 rooma)
		(at item8 rooma)
		(= (weight item11) 2.0)
		(= (weight item12) 2.0)
		(at item16 rooma)
		(door roomd roomb)
		(at item7 rooma)
		(= (weight item3) 1.0)
		(mount left2 bot2)
		(door roomc roomd)
		(at-bot bot1 rooma)
		(door roomb roomd)
		(= (weight item5) 1.0)
		(= (weight item13) 3.0)
		(= (weight item2) 2.0)
		(= (load_limit bot1) 6.0)
		(= (weight item4) 1.0)
		(door roomb rooma)
		(at item12 rooma)
		(= (weight item9) 1.0)
		(door rooma roomb)
		(at item5 rooma)
		(= (weight item8) 1.0)
		(= (weight item6) 1.0)
		(mount left1 bot1)
		(at item9 rooma)
	)
	(:goal
			(and
				(at item16 roomd)
				(at item15 roomd)
				(at item14 roomd)
				(at item13 roomd)
				(at item12 roomb)
				(at item11 roomb)
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomb)
				(at item7 roomb)
				(at item6 roomc)
				(at item5 roomc)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)