(define (problem roverprob5142)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 rover2 rover3 - rover
		rover0store rover1store rover2store rover3store - store
		waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 - waypoint
		camera0 camera1 camera2 camera3 - camera
		objective0 objective1 objective2 objective3 objective4 - objective
	)
	(:init
		(can_traverse rover2 waypoint0 waypoint11)
		(visible_from objective0 waypoint7)
		(visible_from objective4 waypoint1)
		(visible waypoint11 waypoint9)
		(at_soil_sample waypoint11)
		(supports camera2 high_res)
		(= (energy rover0) 50.0)
		(visible waypoint3 waypoint10)
		(= (energy rover3) 50.0)
		(visible waypoint8 waypoint0)
		(available rover3)
		(can_traverse rover0 waypoint7 waypoint10)
		(visible waypoint11 waypoint8)
		(can_traverse rover0 waypoint1 waypoint6)
		(can_traverse rover1 waypoint0 waypoint1)
		(can_traverse rover0 waypoint5 waypoint2)
		(at_rock_sample waypoint10)
		(visible waypoint2 waypoint9)
		(visible waypoint3 waypoint2)
		(can_traverse rover1 waypoint9 waypoint11)
		(visible_from objective1 waypoint5)
		(can_traverse rover0 waypoint1 waypoint3)
		(can_traverse rover0 waypoint11 waypoint7)
		(visible waypoint5 waypoint8)
		(calibration_target camera2 objective2)
		(can_traverse rover3 waypoint11 waypoint0)
		(can_traverse rover2 waypoint9 waypoint3)
		(store_of rover0store rover0)
		(can_traverse rover3 waypoint9 waypoint4)
		(at_rock_sample waypoint11)
		(visible_from objective4 waypoint9)
		(visible waypoint11 waypoint0)
		(visible waypoint2 waypoint10)
		(can_traverse rover2 waypoint2 waypoint5)
		(can_traverse rover2 waypoint11 waypoint0)
		(can_traverse rover2 waypoint1 waypoint9)
		(at_soil_sample waypoint8)
		(can_traverse rover2 waypoint3 waypoint9)
		(visible_from objective4 waypoint7)
		(visible waypoint1 waypoint6)
		(can_traverse rover3 waypoint0 waypoint10)
		(on_board camera1 rover2)
		(can_traverse rover2 waypoint0 waypoint9)
		(on_board camera3 rover2)
		(visible waypoint5 waypoint4)
		(can_traverse rover3 waypoint7 waypoint10)
		(visible_from objective0 waypoint0)
		(calibration_target camera0 objective3)
		(visible waypoint5 waypoint2)
		(can_traverse rover3 waypoint1 waypoint0)
		(= (energy rover2) 50.0)
		(can_traverse rover3 waypoint6 waypoint1)
		(can_traverse rover0 waypoint2 waypoint5)
		(at_rock_sample waypoint9)
		(visible_from objective1 waypoint3)
		(visible waypoint9 waypoint10)
		(at_soil_sample waypoint5)
		(can_traverse rover3 waypoint8 waypoint0)
		(visible waypoint3 waypoint8)
		(visible_from objective2 waypoint7)
		(visible waypoint9 waypoint3)
		(visible_from objective3 waypoint0)
		(can_traverse rover0 waypoint6 waypoint1)
		(visible_from objective0 waypoint8)
		(visible_from objective4 waypoint0)
		(can_traverse rover1 waypoint11 waypoint9)
		(visible waypoint2 waypoint5)
		(visible waypoint4 waypoint9)
		(= (energy rover1) 50.0)
		(visible waypoint11 waypoint7)
		(visible waypoint1 waypoint0)
		(can_traverse rover2 waypoint7 waypoint0)
		(visible waypoint2 waypoint6)
		(visible waypoint10 waypoint1)
		(visible_from objective2 waypoint6)
		(visible_from objective2 waypoint9)
		(visible waypoint8 waypoint10)
		(on_board camera0 rover2)
		(visible waypoint6 waypoint2)
		(can_traverse rover2 waypoint4 waypoint9)
		(visible_from objective4 waypoint2)
		(at_soil_sample waypoint7)
		(visible waypoint4 waypoint3)
		(equipped_for_soil_analysis rover0)
		(visible_from objective2 waypoint4)
		(channel_free general)
		(can_traverse rover3 waypoint0 waypoint8)
		(visible waypoint5 waypoint7)
		(visible waypoint0 waypoint9)
		(available rover0)
		(visible waypoint5 waypoint3)
		(equipped_for_rock_analysis rover0)
		(can_traverse rover3 waypoint1 waypoint3)
		(visible waypoint0 waypoint8)
		(at_rock_sample waypoint5)
		(can_traverse rover1 waypoint1 waypoint3)
		(at_soil_sample waypoint9)
		(available rover2)
		(visible waypoint10 waypoint9)
		(on_board camera2 rover0)
		(can_traverse rover0 waypoint8 waypoint7)
		(visible waypoint0 waypoint10)
		(can_traverse rover3 waypoint3 waypoint1)
		(visible waypoint0 waypoint7)
		(visible_from objective0 waypoint6)
		(visible_from objective1 waypoint2)
		(visible waypoint3 waypoint5)
		(can_traverse rover2 waypoint9 waypoint4)
		(visible waypoint7 waypoint4)
		(can_traverse rover2 waypoint9 waypoint2)
		(visible_from objective4 waypoint8)
		(visible waypoint3 waypoint4)
		(visible waypoint1 waypoint10)
		(can_traverse rover0 waypoint7 waypoint11)
		(can_traverse rover1 waypoint1 waypoint0)
		(at_rock_sample waypoint3)
		(can_traverse rover2 waypoint6 waypoint2)
		(can_traverse rover2 waypoint9 waypoint0)
		(visible_from objective0 waypoint3)
		(can_traverse rover3 waypoint10 waypoint2)
		(visible_from objective2 waypoint1)
		(visible waypoint8 waypoint7)
		(visible waypoint9 waypoint4)
		(can_traverse rover2 waypoint5 waypoint2)
		(visible_from objective4 waypoint5)
		(visible_from objective2 waypoint5)
		(can_traverse rover3 waypoint10 waypoint0)
		(can_traverse rover0 waypoint1 waypoint0)
		(visible waypoint6 waypoint1)
		(visible_from objective4 waypoint6)
		(at_rock_sample waypoint2)
		(visible_from objective2 waypoint3)
		(calibration_target camera1 objective4)
	)
	(:goal
			(and
				(communicated_soil_data waypoint4)
				(communicated_soil_data waypoint9)
				(communicated_soil_data waypoint1)
				(communicated_soil_data waypoint7)
				(communicated_rock_data waypoint3)
				(communicated_rock_data waypoint10)
				(communicated_rock_data waypoint5)
				(communicated_rock_data waypoint1)
				(communicated_image_data objective0 high_res)
				(communicated_image_data objective4 high_res)
				(communicated_image_data objective2 high_res)
			)
	)
)