(define (problem roverprob5142)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 rover2 rover3 - rover
		rover0store rover1store rover2store rover3store - store
		waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 waypoint10 waypoint11 - waypoint
		camera0 camera1 camera2 camera3 - camera
		objective0 objective1 objective2 objective3 objective4 - objective
	)
	(:init
		(can_traverse rover0 waypoint6 waypoint7)
		(can_traverse rover0 waypoint7 waypoint4)
		(visible waypoint10 waypoint7)
		(available rover3)
		(in rover2 waypoint9)
		(visible waypoint11 waypoint4)
		(visible_from objective3 waypoint0)
		(store_of rover1store rover1)
		(can_traverse rover2 waypoint0 waypoint7)
		(visible waypoint6 waypoint2)
		(can_traverse rover0 waypoint5 waypoint2)
		(can_traverse rover1 waypoint4 waypoint2)
		(= (energy rover2) 50.0)
		(visible waypoint0 waypoint11)
		(visible_from objective1 waypoint1)
		(can_traverse rover1 waypoint0 waypoint1)
		(can_traverse rover1 waypoint3 waypoint1)
		(can_traverse rover1 waypoint2 waypoint9)
		(can_traverse rover3 waypoint6 waypoint1)
		(can_traverse rover0 waypoint8 waypoint7)
		(can_traverse rover0 waypoint1 waypoint9)
		(can_traverse rover1 waypoint2 waypoint10)
		(equipped_for_rock_analysis rover3)
		(at_soil_sample waypoint9)
		(can_traverse rover3 waypoint10 waypoint0)
		(can_traverse rover3 waypoint4 waypoint9)
		(can_traverse rover2 waypoint5 waypoint2)
		(can_traverse rover0 waypoint7 waypoint10)
		(visible waypoint11 waypoint9)
		(visible_from objective1 waypoint6)
		(can_traverse rover0 waypoint9 waypoint1)
		(can_traverse rover0 waypoint3 waypoint1)
		(visible waypoint11 waypoint0)
		(in rover1 waypoint2)
		(visible_from objective0 waypoint4)
		(visible_from objective2 waypoint9)
		(visible waypoint9 waypoint4)
		(can_traverse rover1 waypoint5 waypoint2)
		(can_traverse rover0 waypoint0 waypoint1)
		(visible waypoint9 waypoint0)
		(visible_from objective1 waypoint0)
		(visible_from objective1 waypoint2)
		(can_traverse rover3 waypoint9 waypoint0)
		(visible_from objective3 waypoint1)
		(visible_from objective4 waypoint3)
		(visible waypoint4 waypoint9)
		(visible waypoint3 waypoint10)
		(empty rover0store)
		(at_rock_sample waypoint3)
		(visible waypoint9 waypoint2)
		(at_soil_sample waypoint8)
		(visible waypoint2 waypoint9)
		(equipped_for_imaging rover0)
		(at_soil_sample waypoint5)
		(can_traverse rover3 waypoint0 waypoint11)
		(can_traverse rover1 waypoint6 waypoint2)
		(equipped_for_soil_analysis rover1)
		(visible waypoint1 waypoint10)
		(can_traverse rover1 waypoint3 waypoint8)
		(= (energy rover1) 50.0)
		(at_rock_sample waypoint5)
		(visible_from objective0 waypoint2)
		(can_traverse rover1 waypoint1 waypoint0)
		(can_traverse rover2 waypoint9 waypoint3)
		(in rover0 waypoint6)
		(at_rock_sample waypoint8)
	)
	(:goal
			(and
				(communicated_soil_data waypoint4)
				(communicated_soil_data waypoint9)
				(communicated_soil_data waypoint1)
				(communicated_soil_data waypoint7)
				(communicated_rock_data waypoint3)
				(communicated_rock_data waypoint10)
				(communicated_rock_data waypoint5)
				(communicated_rock_data waypoint1)
				(communicated_image_data objective0 high_res)
				(communicated_image_data objective4 high_res)
				(communicated_image_data objective2 high_res)
			)
	)
)