(define (problem mprime-x-21)
	(:domain mystery-prime-typed)
	(:objects
		apple muffin lemon flounder wurst okra snickers onion marzipan popover hamburger guava - food
		triumph satisfaction learning love expectation rest - pleasure
		laceration boils anxiety dread abrasion jealousy prostatitis grief hangover depression angina anger grief-2 sciatica loneliness depression-8 hangover-3 anger-4 angina-1 prostatitis-7 abrasion-6 loneliness-15 sciatica-16 laceration-5 laceration-10 jealousy-11 boils-12 anxiety-13 dread-14 boils-30 grief-31 loneliness-32 hangover-9 abrasion-29 - pain
	)
	(:init
		(craves boils apple)
		(eats wurst flounder)
		(craves jealousy-11 popover)
		(craves abrasion-6 onion)
		(eats snickers wurst)
		(eats snickers apple)
		(eats apple lemon)
		(craves grief-31 hamburger)
		(craves anger flounder)
		(eats hamburger popover)
		(eats flounder wurst)
		(craves loneliness wurst)
		(eats okra hamburger)
		(craves rest guava)
		(eats wurst snickers)
		(craves hangover-9 hamburger)
		(craves anxiety-13 popover)
		(craves grief muffin)
		(eats flounder apple)
		(craves depression lemon)
		(craves laceration-10 popover)
		(craves hangover lemon)
		(craves expectation okra)
		(craves dread-14 popover)
		(= (locale popover) 2.0)
		(eats hamburger okra)
		(eats onion okra)
		(craves angina flounder)
		(eats muffin lemon)
		(= (locale marzipan) 1.0)
		(eats marzipan guava)
		(craves boils-30 hamburger)
		(= (locale apple) 0.0)
		(eats wurst lemon)
		(craves abrasion-29 guava)
		(craves loneliness-15 marzipan)
		(craves sciatica-16 marzipan)
		(craves prostatitis muffin)
		(craves angina-1 okra)
		(eats marzipan snickers)
		(craves loneliness-32 hamburger)
		(= (locale okra) 2.0)
		(craves satisfaction muffin)
		(eats guava marzipan)
		(craves boils-12 popover)
		(= (locale snickers) 2.0)
		(= (harmony triumph) 2.0)
		(craves hangover-3 okra)
		(= (locale muffin) 0.0)
		(craves laceration apple)
		(craves prostatitis-7 snickers)
		(eats snickers popover)
		(craves triumph apple)
		(= (locale hamburger) 1.0)
		(= (locale flounder) 1.0)
		(craves sciatica wurst)
		(= (harmony satisfaction) 3.0)
		(eats popover hamburger)
		(craves grief-2 wurst)
		(eats lemon apple)
		(eats apple snickers)
		(eats lemon wurst)
		(craves anger-4 okra)
		(eats onion guava)
		(= (harmony rest) 1.0)
		(= (locale onion) 0.0)
	)
	(:goal
			(and
				(craves sciatica apple)
			)
	)
)