(define (problem mprime-x-21)
	(:domain mystery-prime-typed)
	(:objects
		apple muffin lemon flounder wurst okra snickers onion marzipan popover hamburger guava - food
		triumph satisfaction learning love expectation rest - pleasure
		laceration boils anxiety dread abrasion jealousy prostatitis grief hangover depression angina anger grief-2 sciatica loneliness depression-8 hangover-3 anger-4 angina-1 prostatitis-7 abrasion-6 loneliness-15 sciatica-16 laceration-5 laceration-10 jealousy-11 boils-12 anxiety-13 dread-14 boils-30 grief-31 loneliness-32 hangover-9 abrasion-29 - pain
	)
	(:init
		(eats lemon wurst)
		(craves anxiety-13 popover)
		(= (locale marzipan) 1.0)
		(= (harmony learning) 3.0)
		(craves depression lemon)
		(eats okra hamburger)
		(craves learning lemon)
		(craves satisfaction muffin)
		(= (locale onion) 0.0)
		(eats apple snickers)
		(= (locale apple) 0.0)
		(eats flounder apple)
		(craves abrasion-6 onion)
		(craves laceration-10 popover)
		(craves loneliness wurst)
		(craves dread-14 popover)
		(craves boils-12 popover)
		(eats marzipan snickers)
		(eats okra onion)
		(eats muffin wurst)
		(craves grief-2 wurst)
		(craves hangover-9 hamburger)
		(eats lemon apple)
		(= (harmony expectation) 2.0)
		(craves prostatitis-7 snickers)
		(craves jealousy muffin)
		(eats popover hamburger)
		(= (harmony love) 2.0)
		(craves anger flounder)
		(craves dread muffin)
		(craves grief-31 hamburger)
		(eats wurst muffin)
		(craves boils-30 hamburger)
		(eats guava marzipan)
		(craves sciatica wurst)
		(craves angina-1 okra)
		(eats onion guava)
		(craves abrasion-29 guava)
		(craves rest guava)
		(= (locale wurst) 0.0)
		(craves love flounder)
		(= (locale popover) 2.0)
		(= (locale guava) 1.0)
		(craves boils apple)
	)
	(:goal
			(and
				(craves sciatica apple)
			)
	)
)