(define (problem roverprob2312)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 - rover
		rover0store rover1store - store
		waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 - waypoint
		camera0 camera1 camera2 - camera
		objective0 objective1 - objective
	)
	(:init
		(can_traverse rover1 waypoint1 waypoint4)
		(visible_from objective1 waypoint0)
		(can_traverse rover1 waypoint5 waypoint2)
		(can_traverse rover1 waypoint2 waypoint5)
		(at_soil_sample waypoint5)
		(visible waypoint4 waypoint5)
		(supports camera2 colour)
		(at_rock_sample waypoint2)
		(visible waypoint2 waypoint5)
		(visible waypoint3 waypoint2)
		(available rover1)
		(can_traverse rover1 waypoint0 waypoint1)
		(visible waypoint3 waypoint4)
		(at_rock_sample waypoint3)
		(calibration_target camera0 objective0)
		(at_rock_sample waypoint0)
		(visible waypoint5 waypoint4)
		(visible_from objective0 waypoint4)
		(at_soil_sample waypoint3)
		(available rover0)
		(visible_from objective0 waypoint1)
		(visible waypoint5 waypoint2)
		(supports camera0 colour)
		(can_traverse rover1 waypoint4 waypoint5)
		(on_board camera2 rover1)
		(visible_from objective1 waypoint1)
		(supports camera2 high_res)
		(visible waypoint2 waypoint3)
		(can_traverse rover0 waypoint0 waypoint3)
		(on_board camera1 rover0)
		(= (recharges) 0.0)
		(at_soil_sample waypoint2)
		(visible waypoint4 waypoint1)
		(can_traverse rover0 waypoint0 waypoint5)
		(can_traverse rover0 waypoint0 waypoint1)
		(supports camera0 low_res)
		(visible_from objective0 waypoint0)
		(visible waypoint3 waypoint5)
		(visible waypoint1 waypoint0)
		(at_soil_sample waypoint4)
		(visible waypoint0 waypoint1)
		(can_traverse rover0 waypoint1 waypoint4)
		(can_traverse rover1 waypoint4 waypoint3)
		(can_traverse rover0 waypoint1 waypoint0)
		(supports camera1 low_res)
		(visible waypoint3 waypoint0)
		(can_traverse rover0 waypoint0 waypoint2)
		(can_traverse rover0 waypoint3 waypoint0)
		(equipped_for_imaging rover0)
		(visible waypoint3 waypoint1)
		(calibration_target camera2 objective0)
		(in rover0 waypoint1)
		(can_traverse rover1 waypoint3 waypoint4)
		(equipped_for_imaging rover1)
		(visible waypoint0 waypoint3)
		(at_rock_sample waypoint5)
		(empty rover1store)
		(can_traverse rover1 waypoint1 waypoint0)
		(equipped_for_rock_analysis rover0)
		(empty rover0store)
		(calibration_target camera1 objective1)
		(can_traverse rover0 waypoint2 waypoint0)
		(visible waypoint2 waypoint0)
		(equipped_for_soil_analysis rover1)
		(visible waypoint0 waypoint5)
		(visible waypoint1 waypoint4)
	)
	(:goal
			(and
				(communicated_soil_data waypoint5)
				(communicated_soil_data waypoint1)
				(communicated_soil_data waypoint4)
				(communicated_soil_data waypoint2)
				(communicated_rock_data waypoint0)
				(communicated_rock_data waypoint2)
				(communicated_rock_data waypoint3)
				(communicated_image_data objective0 colour)
				(communicated_image_data objective1 low_res)
				(communicated_image_data objective0 low_res)
			)
	)
)