(define (problem mprime-x-9)
	(:domain mystery-prime-typed)
	(:objects
		apple flounder haroset hamburger wurst hotdog guava - food
		entertainment intoxication curiosity excitement - pleasure
		dread sciatica abrasion prostatitis loneliness anger hangover anxiety laceration boils jealousy angina grief - pain
	)
	(:init
		(craves loneliness haroset)
		(eats wurst flounder)
		(craves abrasion haroset)
		(eats wurst hotdog)
		(eats flounder hamburger)
		(craves anger haroset)
		(craves hangover haroset)
		(= (locale hotdog) 1.0)
		(= (harmony intoxication) 1.0)
		(= (harmony curiosity) 1.0)
		(= (locale flounder) 2.0)
		(eats haroset guava)
		(= (harmony excitement) 1.0)
		(craves jealousy guava)
		(craves sciatica flounder)
		(= (locale wurst) 1.0)
		(eats apple guava)
		(craves prostatitis haroset)
		(eats hotdog wurst)
		(= (locale guava) 4.0)
		(= (locale hamburger) 0.0)
		(craves curiosity hotdog)
		(eats guava haroset)
		(eats flounder wurst)
		(craves anxiety wurst)
		(eats hamburger flounder)
		(craves intoxication haroset)
		(eats haroset hamburger)
		(eats hotdog apple)
		(craves boils guava)
		(eats apple hotdog)
		(craves entertainment flounder)
		(craves laceration wurst)
		(= (harmony entertainment) 3.0)
		(eats guava apple)
		(craves angina guava)
		(craves dread flounder)
		(craves excitement guava)
		(= (locale haroset) 2.0)
		(craves grief guava)
		(eats hamburger haroset)
		(= (locale apple) 2.0)
	)
	(:goal
			(and
				(craves sciatica hamburger)
				(craves jealousy wurst)
			)
	)
)