(define (problem mprime-x-9)
	(:domain mystery-prime-typed)
	(:objects
		apple flounder haroset hamburger wurst hotdog guava - food
		entertainment intoxication curiosity excitement - pleasure
		dread sciatica abrasion prostatitis loneliness anger hangover anxiety laceration boils jealousy angina grief - pain
	)
	(:init
		(craves loneliness haroset)
		(= (locale wurst) 1.0)
		(craves entertainment flounder)
		(= (locale flounder) 2.0)
		(= (harmony curiosity) 1.0)
		(= (locale hotdog) 1.0)
		(= (harmony excitement) 1.0)
		(craves boils guava)
		(eats haroset hamburger)
		(craves abrasion haroset)
		(= (harmony intoxication) 1.0)
		(= (locale guava) 4.0)
		(= (locale haroset) 2.0)
		(eats guava haroset)
		(eats hotdog wurst)
		(craves prostatitis haroset)
		(eats flounder wurst)
		(craves jealousy guava)
		(eats guava apple)
		(craves sciatica flounder)
		(eats hotdog apple)
		(craves anxiety wurst)
		(= (locale hamburger) 0.0)
		(craves dread flounder)
		(= (harmony entertainment) 3.0)
		(eats hamburger haroset)
		(eats apple hotdog)
		(= (locale apple) 2.0)
		(craves intoxication haroset)
		(craves excitement guava)
		(eats wurst flounder)
	)
	(:goal
			(and
				(craves sciatica hamburger)
				(craves jealousy wurst)
			)
	)
)