(define (problem roverprob7126)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 rover2 rover3 - rover
		rover0store rover1store rover2store rover3store - store
		waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 - waypoint
		camera0 camera1 camera2 camera3 - camera
		objective0 objective1 objective2 - objective
	)
	(:init
		(visible waypoint1 waypoint7)
		(can_traverse rover0 waypoint6 waypoint0)
		(equipped_for_imaging rover1)
		(visible_from objective0 waypoint0)
		(can_traverse rover1 waypoint3 waypoint7)
		(equipped_for_soil_analysis rover0)
		(store_of rover1store rover1)
		(can_traverse rover3 waypoint1 waypoint2)
		(visible_from objective1 waypoint2)
		(at_lander general waypoint1)
		(can_traverse rover0 waypoint0 waypoint1)
		(can_traverse rover0 waypoint1 waypoint4)
		(visible waypoint4 waypoint5)
		(visible_from objective1 waypoint1)
		(in rover2 waypoint3)
		(can_traverse rover1 waypoint2 waypoint7)
		(visible_from objective2 waypoint1)
		(visible waypoint7 waypoint1)
		(on_board camera2 rover3)
		(empty rover2store)
		(can_traverse rover0 waypoint1 waypoint5)
		(can_traverse rover2 waypoint3 waypoint0)
		(can_traverse rover0 waypoint0 waypoint7)
		(can_traverse rover2 waypoint3 waypoint6)
		(supports camera1 high_res)
		(equipped_for_imaging rover0)
		(empty rover0store)
		(store_of rover2store rover2)
		(visible waypoint6 waypoint2)
		(visible_from objective1 waypoint0)
		(can_traverse rover0 waypoint4 waypoint1)
		(visible waypoint4 waypoint0)
		(visible waypoint6 waypoint4)
		(on_board camera1 rover2)
		(visible waypoint1 waypoint0)
		(equipped_for_soil_analysis rover3)
		(at_rock_sample waypoint4)
		(visible waypoint2 waypoint3)
		(at_soil_sample waypoint1)
		(visible waypoint0 waypoint4)
		(can_traverse rover2 waypoint4 waypoint0)
		(= (energy rover3) 50.0)
		(can_traverse rover3 waypoint0 waypoint4)
	)
	(:goal
			(and
				(communicated_soil_data waypoint6)
				(communicated_soil_data waypoint0)
				(communicated_soil_data waypoint1)
				(communicated_soil_data waypoint3)
				(communicated_rock_data waypoint6)
				(communicated_rock_data waypoint0)
				(communicated_rock_data waypoint4)
				(communicated_rock_data waypoint7)
				(communicated_image_data objective1 high_res)
			)
	)
)