(define (problem roverprob6152)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 rover2 rover3 - rover
		rover0store rover1store rover2store rover3store - store
		waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 - waypoint
		camera0 camera1 camera2 camera3 camera4 - camera
		objective0 objective1 objective2 objective3 - objective
	)
	(:init
		(can_traverse rover1 waypoint0 waypoint6)
		(on_board camera1 rover2)
		(can_traverse rover2 waypoint0 waypoint3)
		(at_rock_sample waypoint1)
		(can_traverse rover0 waypoint1 waypoint3)
		(visible waypoint0 waypoint1)
		(can_traverse rover1 waypoint4 waypoint2)
		(visible waypoint7 waypoint1)
		(visible waypoint3 waypoint1)
		(equipped_for_soil_analysis rover0)
		(can_traverse rover0 waypoint3 waypoint1)
		(can_traverse rover0 waypoint6 waypoint0)
		(in rover0 waypoint7)
		(can_traverse rover2 waypoint2 waypoint6)
		(visible waypoint0 waypoint6)
		(can_traverse rover0 waypoint1 waypoint7)
		(can_traverse rover3 waypoint3 waypoint7)
		(in rover1 waypoint6)
		(can_traverse rover3 waypoint1 waypoint3)
		(equipped_for_imaging rover1)
		(can_traverse rover1 waypoint0 waypoint2)
		(can_traverse rover0 waypoint5 waypoint1)
		(visible_from objective2 waypoint3)
		(on_board camera0 rover2)
		(visible waypoint2 waypoint4)
		(visible waypoint3 waypoint8)
		(can_traverse rover3 waypoint3 waypoint1)
		(supports camera0 high_res)
		(visible waypoint4 waypoint2)
		(can_traverse rover0 waypoint7 waypoint1)
		(= (energy rover2) 50.0)
		(equipped_for_imaging rover0)
		(at_rock_sample waypoint6)
		(can_traverse rover2 waypoint0 waypoint5)
		(visible_from objective3 waypoint2)
		(on_board camera3 rover1)
		(visible_from objective0 waypoint0)
		(visible waypoint3 waypoint7)
		(can_traverse rover1 waypoint6 waypoint0)
		(can_traverse rover2 waypoint6 waypoint2)
		(at_soil_sample waypoint7)
		(can_traverse rover3 waypoint7 waypoint3)
		(at_rock_sample waypoint8)
		(at_lander general waypoint2)
		(visible waypoint5 waypoint0)
		(available rover3)
		(visible waypoint1 waypoint2)
		(visible waypoint2 waypoint7)
		(can_traverse rover3 waypoint1 waypoint2)
		(visible_from objective1 waypoint6)
	)
	(:goal
			(and
				(communicated_soil_data waypoint7)
				(communicated_soil_data waypoint5)
				(communicated_soil_data waypoint2)
				(communicated_soil_data waypoint4)
				(communicated_rock_data waypoint4)
				(communicated_rock_data waypoint6)
				(communicated_rock_data waypoint7)
				(communicated_rock_data waypoint8)
				(communicated_rock_data waypoint1)
				(communicated_image_data objective3 high_res)
				(communicated_image_data objective1 high_res)
				(communicated_image_data objective2 high_res)
			)
	)
)