(define (problem roverprob6152)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 rover2 rover3 - rover
		rover0store rover1store rover2store rover3store - store
		waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 - waypoint
		camera0 camera1 camera2 camera3 camera4 - camera
		objective0 objective1 objective2 objective3 - objective
	)
	(:init
		(in rover0 waypoint7)
		(visible waypoint8 waypoint2)
		(can_traverse rover3 waypoint8 waypoint3)
		(equipped_for_rock_analysis rover2)
		(visible_from objective2 waypoint1)
		(on_board camera4 rover0)
		(supports camera1 low_res)
		(visible_from objective3 waypoint0)
		(visible waypoint3 waypoint8)
		(visible waypoint3 waypoint0)
		(at_rock_sample waypoint4)
		(can_traverse rover1 waypoint2 waypoint8)
		(can_traverse rover3 waypoint0 waypoint4)
		(in rover2 waypoint6)
		(visible waypoint0 waypoint1)
		(can_traverse rover1 waypoint3 waypoint0)
		(can_traverse rover2 waypoint0 waypoint5)
		(available rover0)
		(visible_from objective2 waypoint2)
		(visible_from objective1 waypoint4)
		(visible waypoint2 waypoint4)
		(can_traverse rover0 waypoint6 waypoint0)
		(store_of rover2store rover2)
		(visible waypoint0 waypoint6)
		(can_traverse rover2 waypoint5 waypoint0)
		(calibration_target camera2 objective1)
		(visible waypoint7 waypoint1)
		(= (recharges) 0.0)
		(can_traverse rover3 waypoint4 waypoint0)
		(in_sun waypoint7)
		(can_traverse rover2 waypoint1 waypoint0)
		(visible waypoint5 waypoint1)
		(visible waypoint7 waypoint3)
		(empty rover2store)
		(can_traverse rover0 waypoint0 waypoint7)
		(at_soil_sample waypoint5)
		(visible waypoint4 waypoint8)
		(calibration_target camera0 objective1)
		(can_traverse rover1 waypoint2 waypoint0)
		(can_traverse rover1 waypoint8 waypoint2)
		(= (energy rover1) 50.0)
		(visible waypoint2 waypoint8)
		(in rover3 waypoint3)
		(can_traverse rover3 waypoint3 waypoint0)
		(can_traverse rover1 waypoint0 waypoint3)
		(can_traverse rover3 waypoint3 waypoint8)
		(can_traverse rover2 waypoint6 waypoint2)
		(can_traverse rover3 waypoint3 waypoint7)
		(visible waypoint2 waypoint7)
		(equipped_for_imaging rover1)
		(visible waypoint0 waypoint5)
		(visible waypoint5 waypoint3)
		(at_lander general waypoint2)
		(can_traverse rover2 waypoint4 waypoint0)
		(visible waypoint3 waypoint1)
		(visible waypoint1 waypoint5)
		(can_traverse rover0 waypoint8 waypoint7)
		(supports camera0 high_res)
		(visible waypoint4 waypoint2)
		(visible_from objective3 waypoint6)
		(can_traverse rover2 waypoint0 waypoint4)
		(can_traverse rover1 waypoint0 waypoint2)
		(can_traverse rover2 waypoint2 waypoint8)
		(can_traverse rover0 waypoint3 waypoint1)
		(can_traverse rover0 waypoint7 waypoint2)
		(visible waypoint2 waypoint1)
		(visible waypoint6 waypoint7)
		(visible_from objective1 waypoint2)
		(can_traverse rover1 waypoint6 waypoint0)
		(on_board camera0 rover2)
		(visible waypoint7 waypoint0)
		(store_of rover1store rover1)
		(at_rock_sample waypoint7)
		(visible waypoint1 waypoint7)
		(store_of rover3store rover3)
		(visible_from objective1 waypoint3)
		(visible waypoint7 waypoint6)
		(visible waypoint8 waypoint4)
		(can_traverse rover0 waypoint5 waypoint1)
		(visible_from objective2 waypoint5)
		(available rover2)
		(visible waypoint4 waypoint0)
		(in rover1 waypoint6)
		(can_traverse rover3 waypoint5 waypoint3)
		(can_traverse rover3 waypoint1 waypoint3)
		(visible_from objective3 waypoint4)
		(visible_from objective0 waypoint0)
		(visible waypoint1 waypoint2)
		(equipped_for_rock_analysis rover3)
		(can_traverse rover3 waypoint2 waypoint1)
		(calibration_target camera4 objective1)
		(can_traverse rover1 waypoint4 waypoint2)
		(visible_from objective2 waypoint0)
		(empty rover3store)
		(can_traverse rover1 waypoint3 waypoint1)
		(= (energy rover0) 50.0)
		(visible waypoint4 waypoint3)
		(visible waypoint5 waypoint2)
		(at_rock_sample waypoint8)
		(can_traverse rover3 waypoint3 waypoint1)
		(can_traverse rover2 waypoint7 waypoint6)
		(can_traverse rover0 waypoint7 waypoint1)
		(can_traverse rover1 waypoint0 waypoint6)
		(visible waypoint6 waypoint0)
		(at_rock_sample waypoint6)
		(can_traverse rover3 waypoint3 waypoint5)
		(visible_from objective3 waypoint1)
		(visible waypoint2 waypoint0)
		(at_soil_sample waypoint2)
		(visible_from objective3 waypoint2)
		(can_traverse rover3 waypoint0 waypoint6)
		(equipped_for_soil_analysis rover0)
		(can_traverse rover2 waypoint2 waypoint6)
		(visible waypoint7 waypoint2)
		(visible_from objective1 waypoint1)
		(visible_from objective3 waypoint3)
		(can_traverse rover0 waypoint2 waypoint4)
		(equipped_for_soil_analysis rover1)
		(can_traverse rover0 waypoint0 waypoint6)
		(visible waypoint4 waypoint1)
		(available rover3)
		(on_board camera2 rover3)
		(can_traverse rover0 waypoint7 waypoint8)
		(equipped_for_soil_analysis rover2)
		(can_traverse rover3 waypoint6 waypoint0)
		(can_traverse rover3 waypoint1 waypoint2)
		(visible waypoint1 waypoint4)
		(visible waypoint7 waypoint8)
		(can_traverse rover0 waypoint1 waypoint3)
		(visible waypoint3 waypoint5)
		(= (energy rover3) 50.0)
		(visible_from objective3 waypoint7)
		(on_board camera1 rover2)
		(visible waypoint3 waypoint4)
		(supports camera2 high_res)
		(visible waypoint0 waypoint4)
		(empty rover0store)
		(visible_from objective1 waypoint5)
		(can_traverse rover2 waypoint0 waypoint3)
		(available rover1)
		(= (energy rover2) 50.0)
		(visible waypoint1 waypoint0)
		(visible_from objective1 waypoint0)
		(equipped_for_imaging rover3)
		(visible_from objective3 waypoint5)
		(at_rock_sample waypoint2)
		(can_traverse rover3 waypoint7 waypoint3)
		(can_traverse rover2 waypoint6 waypoint0)
		(on_board camera3 rover1)
		(can_traverse rover2 waypoint0 waypoint1)
		(visible waypoint0 waypoint7)
		(can_traverse rover0 waypoint1 waypoint5)
		(visible waypoint2 waypoint6)
		(visible waypoint3 waypoint7)
		(supports camera4 high_res)
		(at_soil_sample waypoint7)
		(visible waypoint5 waypoint0)
		(visible waypoint8 waypoint7)
		(at_soil_sample waypoint4)
		(visible waypoint1 waypoint8)
		(can_traverse rover1 waypoint7 waypoint0)
		(visible waypoint6 waypoint2)
		(can_traverse rover2 waypoint3 waypoint0)
		(supports camera1 colour)
		(empty rover1store)
		(supports camera3 low_res)
		(can_traverse rover0 waypoint1 waypoint7)
		(calibration_target camera3 objective2)
		(can_traverse rover2 waypoint8 waypoint2)
		(at_rock_sample waypoint0)
		(can_traverse rover3 waypoint0 waypoint3)
		(in_sun waypoint3)
		(can_traverse rover2 waypoint6 waypoint7)
		(visible waypoint1 waypoint3)
		(can_traverse rover0 waypoint2 waypoint7)
		(visible_from objective2 waypoint4)
		(visible_from objective1 waypoint7)
		(channel_free general)
		(equipped_for_soil_analysis rover3)
		(visible waypoint0 waypoint3)
		(visible_from objective2 waypoint3)
		(can_traverse rover1 waypoint1 waypoint3)
		(visible waypoint0 waypoint2)
		(can_traverse rover1 waypoint2 waypoint4)
		(visible_from objective1 waypoint6)
		(visible waypoint8 waypoint3)
		(calibration_target camera1 objective1)
		(can_traverse rover2 waypoint0 waypoint6)
		(supports camera4 low_res)
		(visible waypoint8 waypoint1)
		(equipped_for_imaging rover0)
		(can_traverse rover0 waypoint7 waypoint0)
		(can_traverse rover1 waypoint0 waypoint7)
		(supports camera0 colour)
		(can_traverse rover0 waypoint4 waypoint2)
		(store_of rover0store rover0)
		(visible waypoint2 waypoint5)
		(equipped_for_imaging rover2)
		(supports camera3 colour)
		(at_rock_sample waypoint1)
	)
	(:goal
			(and
				(communicated_soil_data waypoint7)
				(communicated_soil_data waypoint5)
				(communicated_soil_data waypoint2)
				(communicated_soil_data waypoint4)
				(communicated_rock_data waypoint4)
				(communicated_rock_data waypoint6)
				(communicated_rock_data waypoint7)
				(communicated_rock_data waypoint8)
				(communicated_rock_data waypoint1)
				(communicated_image_data objective3 high_res)
				(communicated_image_data objective1 high_res)
				(communicated_image_data objective2 high_res)
			)
	)
)