(define (problem mprime-x-5)
	(:domain mystery-prime-typed)
	(:objects
		broccoli chocolate turkey tuna sweetroll shrimp cherry scallop - food
		satisfaction excitement intoxication lubricity - pleasure
		sciatica anxiety grief boils depression abrasion prostatitis angina jealousy laceration anger grief-2 dread loneliness hangover - pain
	)
	(:init
		(eats broccoli chocolate)
		(eats tuna turkey)
		(= (locale broccoli) 3.0)
		(eats chocolate shrimp)
		(eats tuna broccoli)
		(craves anxiety broccoli)
		(craves dread scallop)
		(eats broccoli tuna)
		(craves hangover scallop)
		(eats turkey tuna)
		(eats chocolate broccoli)
		(eats chocolate turkey)
		(craves grief broccoli)
		(= (locale sweetroll) 0.0)
		(= (locale tuna) 3.0)
		(craves angina shrimp)
		(craves boils broccoli)
		(= (locale chocolate) 2.0)
		(= (locale turkey) 1.0)
		(= (harmony lubricity) 2.0)
		(craves grief-2 scallop)
		(craves intoxication tuna)
		(eats turkey chocolate)
		(= (harmony intoxication) 2.0)
		(craves laceration shrimp)
		(eats scallop cherry)
		(craves excitement turkey)
		(eats shrimp sweetroll)
		(eats scallop sweetroll)
		(craves jealousy shrimp)
		(eats cherry shrimp)
		(craves satisfaction broccoli)
		(craves lubricity sweetroll)
		(= (locale scallop) 0.0)
		(eats cherry scallop)
		(eats shrimp chocolate)
		(= (locale cherry) 1.0)
		(craves loneliness scallop)
		(craves anger cherry)
		(= (harmony excitement) 3.0)
		(= (harmony satisfaction) 2.0)
		(eats sweetroll shrimp)
		(eats shrimp cherry)
		(craves sciatica broccoli)
		(= (locale shrimp) 1.0)
		(craves abrasion turkey)
		(eats sweetroll scallop)
		(craves depression turkey)
		(craves prostatitis turkey)
	)
	(:goal
			(and
				(craves loneliness shrimp)
				(craves grief shrimp)
			)
	)
)