(define (problem mprime-x-5)
	(:domain mystery-prime-typed)
	(:objects
		broccoli chocolate turkey tuna sweetroll shrimp cherry scallop - food
		satisfaction excitement intoxication lubricity - pleasure
		sciatica anxiety grief boils depression abrasion prostatitis angina jealousy laceration anger grief-2 dread loneliness hangover - pain
	)
	(:init
		(= (locale cherry) 1.0)
		(= (locale shrimp) 1.0)
		(eats chocolate shrimp)
		(craves anxiety broccoli)
		(eats broccoli tuna)
		(eats cherry shrimp)
		(= (locale chocolate) 2.0)
		(craves boils broccoli)
		(eats turkey chocolate)
		(craves sciatica broccoli)
		(craves abrasion turkey)
		(craves excitement turkey)
		(craves angina shrimp)
		(craves laceration shrimp)
		(= (harmony satisfaction) 2.0)
		(= (harmony lubricity) 2.0)
		(eats scallop sweetroll)
		(= (harmony excitement) 3.0)
		(eats chocolate turkey)
		(craves hangover scallop)
		(= (locale tuna) 3.0)
		(= (harmony intoxication) 2.0)
		(eats chocolate broccoli)
		(eats sweetroll scallop)
		(craves prostatitis turkey)
		(eats cherry scallop)
		(eats broccoli chocolate)
		(eats sweetroll shrimp)
		(craves depression turkey)
		(craves grief-2 scallop)
		(craves satisfaction broccoli)
		(eats shrimp chocolate)
		(craves jealousy shrimp)
		(= (locale scallop) 0.0)
		(= (locale sweetroll) 0.0)
		(craves anger cherry)
	)
	(:goal
			(and
				(craves loneliness shrimp)
				(craves grief shrimp)
			)
	)
)