(define (problem mprime-x-20)
	(:domain mystery-prime-typed)
	(:objects
		mutton cod muffin tuna pork sweetroll yogurt wonderbread turkey pepper rice guava potato orange baguette scallion marzipan cherry - food
		love curiosity aesthetics empathy satisfaction triumph intoxication lubricity expectation understanding achievement - pleasure
		dread abrasion grief laceration - pain
	)
	(:init
		(eats pepper guava)
		(eats scallion orange)
		(eats orange marzipan)
		(eats rice potato)
		(eats pork cod)
		(craves intoxication wonderbread)
		(eats tuna cod)
		(eats muffin yogurt)
		(= (harmony satisfaction) 2.0)
		(= (locale cherry) 7.0)
		(eats pork mutton)
		(= (locale pork) 2.0)
		(= (harmony understanding) 1.0)
		(craves empathy pork)
		(eats tuna turkey)
		(= (locale mutton) 2.0)
		(eats turkey rice)
		(eats guava pepper)
		(eats pork sweetroll)
		(eats potato rice)
		(eats marzipan cherry)
		(= (harmony curiosity) 1.0)
		(= (locale potato) 10.0)
		(eats cherry turkey)
		(eats cherry marzipan)
		(eats baguette guava)
		(eats guava turkey)
		(eats scallion potato)
		(= (locale sweetroll) 7.0)
		(eats muffin sweetroll)
		(eats guava baguette)
		(= (locale cod) 7.0)
		(eats mutton pork)
		(= (locale muffin) 8.0)
		(eats orange scallion)
		(= (locale tuna) 8.0)
		(craves expectation orange)
		(eats sweetroll tuna)
		(= (harmony aesthetics) 1.0)
		(= (locale rice) 0.0)
		(= (harmony lubricity) 3.0)
		(= (harmony achievement) 2.0)
		(= (locale scallion) 10.0)
		(craves satisfaction sweetroll)
		(= (locale pepper) 11.0)
		(eats tuna sweetroll)
		(craves triumph yogurt)
		(eats turkey guava)
		(= (harmony expectation) 2.0)
		(= (locale marzipan) 5.0)
		(craves lubricity rice)
		(eats turkey tuna)
		(eats cod pork)
		(= (harmony intoxication) 2.0)
		(= (locale yogurt) 8.0)
		(= (locale guava) 7.0)
		(= (harmony empathy) 1.0)
		(eats cod tuna)
		(craves aesthetics muffin)
		(eats cherry pepper)
		(eats potato scallion)
		(eats yogurt muffin)
		(= (harmony love) 1.0)
		(eats sweetroll muffin)
		(eats yogurt tuna)
		(craves grief turkey)
		(eats baguette rice)
		(eats cod marzipan)
		(= (locale orange) 2.0)
	)
	(:goal
			(and
				(craves abrasion pepper)
			)
	)
)