(define (problem mprime-x-20)
	(:domain mystery-prime-typed)
	(:objects
		mutton cod muffin tuna pork sweetroll yogurt wonderbread turkey pepper rice guava potato orange baguette scallion marzipan cherry - food
		love curiosity aesthetics empathy satisfaction triumph intoxication lubricity expectation understanding achievement - pleasure
		dread abrasion grief laceration - pain
	)
	(:init
		(eats baguette rice)
		(= (locale pepper) 11.0)
		(= (locale cherry) 7.0)
		(= (locale muffin) 8.0)
		(= (locale sweetroll) 7.0)
		(eats pork cod)
		(= (locale turkey) 3.0)
		(eats scallion orange)
		(craves love mutton)
		(craves intoxication wonderbread)
		(eats marzipan orange)
		(eats tuna turkey)
		(= (locale marzipan) 5.0)
		(eats pepper guava)
		(craves aesthetics muffin)
		(eats pork mutton)
		(= (locale orange) 2.0)
		(= (harmony intoxication) 2.0)
		(craves abrasion wonderbread)
		(eats cod pork)
		(eats mutton pork)
		(= (harmony aesthetics) 1.0)
		(eats orange scallion)
		(= (locale baguette) 2.0)
		(eats pepper cherry)
		(eats cherry turkey)
		(= (locale rice) 0.0)
		(eats muffin yogurt)
		(= (locale wonderbread) 6.0)
		(craves empathy pork)
		(eats orange marzipan)
		(eats yogurt wonderbread)
		(eats wonderbread yogurt)
		(eats guava baguette)
		(= (locale pork) 2.0)
		(eats cherry pepper)
		(craves laceration cherry)
		(= (harmony lubricity) 3.0)
		(eats tuna cod)
		(eats turkey cherry)
		(eats tuna yogurt)
		(craves achievement cherry)
		(= (harmony expectation) 2.0)
		(= (harmony love) 1.0)
		(eats turkey rice)
		(craves curiosity cod)
		(craves triumph yogurt)
		(craves expectation orange)
		(eats marzipan cod)
		(eats guava turkey)
		(eats mutton wonderbread)
		(eats sweetroll muffin)
		(eats wonderbread mutton)
		(eats yogurt tuna)
		(= (locale scallion) 10.0)
		(eats muffin sweetroll)
		(craves grief turkey)
		(eats tuna sweetroll)
		(craves lubricity rice)
		(eats guava pepper)
		(eats baguette guava)
		(eats turkey guava)
		(craves dread yogurt)
		(eats marzipan cherry)
		(eats rice potato)
		(eats sweetroll pork)
		(eats cod marzipan)
		(= (harmony satisfaction) 2.0)
		(eats rice baguette)
		(= (harmony empathy) 1.0)
		(eats potato rice)
		(= (harmony triumph) 2.0)
		(eats potato scallion)
		(= (locale tuna) 8.0)
		(= (locale potato) 10.0)
		(= (locale guava) 7.0)
		(= (harmony curiosity) 1.0)
		(= (harmony achievement) 2.0)
		(eats scallion potato)
		(= (locale yogurt) 8.0)
		(= (locale cod) 7.0)
		(eats turkey tuna)
		(eats pork sweetroll)
		(eats rice turkey)
		(= (locale mutton) 2.0)
		(eats sweetroll tuna)
		(= (harmony understanding) 1.0)
		(craves satisfaction sweetroll)
		(craves understanding marzipan)
		(eats cherry marzipan)
		(eats cod tuna)
		(eats yogurt muffin)
	)
	(:goal
			(and
				(craves abrasion pepper)
			)
	)
)