(define (problem delivery-x-5)
	(:domain delivery)
	(:objects
		rooma roomb roomc - room
		item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(at item3 rooma)
		(mount right1 bot1)
		(at item2 rooma)
		(= (weight item3) 1.0)
		(= (load_limit bot2) 4.0)
		(= (weight item11) 2.0)
		(door roomc rooma)
		(at item6 rooma)
		(at item9 rooma)
		(= (load_limit bot1) 4.0)
		(= (weight item1) 1.0)
		(= (weight item7) 1.0)
		(at item12 rooma)
		(= (weight item5) 2.0)
		(mount left2 bot2)
		(at item10 rooma)
		(free right2)
		(= (cost) 0.0)
		(at-bot bot2 rooma)
		(door rooma roomc)
		(mount left1 bot1)
		(at item5 rooma)
		(at item4 rooma)
		(door roomb rooma)
		(door rooma roomb)
		(mount right2 bot2)
		(= (weight item2) 1.0)
		(at item7 rooma)
		(free left1)
		(at item1 rooma)
		(= (current_load bot2) 0.0)
		(free left2)
	)
	(:goal
			(and
				(at item12 roomb)
				(at item11 roomb)
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomb)
				(at item7 roomb)
				(at item6 roomc)
				(at item5 roomc)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)