(define (problem mprime-x-4)
	(:domain mystery-prime-typed)
	(:objects
		muffin ham scallion shrimp cherry grapefruit bacon arugula scallop wurst - food
		aesthetics - pleasure
		hangover dread sciatica jealousy loneliness abrasion anger - pain
	)
	(:init
		(eats muffin ham)
		(eats wurst arugula)
		(eats scallop arugula)
		(eats arugula wurst)
		(eats grapefruit scallop)
		(eats cherry ham)
		(eats bacon arugula)
		(craves dread ham)
		(eats muffin cherry)
		(eats ham cherry)
		(= (harmony aesthetics) 1.0)
		(eats arugula muffin)
		(eats grapefruit wurst)
		(craves aesthetics shrimp)
		(eats muffin scallion)
		(eats shrimp scallion)
		(= (locale scallop) 3.0)
		(= (locale grapefruit) 0.0)
		(craves jealousy bacon)
		(eats shrimp cherry)
		(craves abrasion scallop)
		(= (locale cherry) 4.0)
		(eats arugula bacon)
		(craves anger wurst)
		(craves loneliness arugula)
		(eats arugula cherry)
		(eats ham muffin)
		(eats wurst grapefruit)
		(= (locale scallion) 1.0)
		(eats scallion shrimp)
		(eats cherry shrimp)
		(= (locale arugula) 4.0)
		(craves hangover muffin)
		(eats muffin arugula)
		(eats cherry muffin)
	)
	(:goal
			(and
				(craves sciatica wurst)
			)
	)
)