(define (problem mprime-x-4)
	(:domain mystery-prime-typed)
	(:objects
		muffin ham scallion shrimp cherry grapefruit bacon arugula scallop wurst - food
		aesthetics - pleasure
		hangover dread sciatica jealousy loneliness abrasion anger - pain
	)
	(:init
		(eats cherry ham)
		(eats cherry muffin)
		(= (locale wurst) 0.0)
		(= (locale cherry) 4.0)
		(craves abrasion scallop)
		(eats arugula muffin)
		(eats wurst bacon)
		(craves aesthetics shrimp)
		(= (locale ham) 2.0)
		(eats muffin scallion)
		(= (harmony aesthetics) 1.0)
		(craves dread ham)
		(= (locale scallop) 3.0)
		(eats arugula cherry)
		(craves sciatica grapefruit)
		(eats bacon arugula)
		(eats scallion shrimp)
		(craves loneliness arugula)
		(eats shrimp scallion)
		(eats muffin arugula)
		(eats wurst grapefruit)
		(eats grapefruit wurst)
		(eats muffin ham)
		(eats scallop arugula)
		(= (locale arugula) 4.0)
		(= (locale bacon) 1.0)
		(eats shrimp cherry)
		(eats ham cherry)
		(craves hangover muffin)
		(eats ham muffin)
		(craves jealousy bacon)
		(= (locale scallion) 1.0)
		(eats arugula wurst)
		(eats wurst arugula)
		(eats bacon wurst)
		(craves anger wurst)
		(eats arugula scallop)
		(eats arugula bacon)
		(= (locale grapefruit) 0.0)
		(eats cherry shrimp)
		(eats grapefruit scallop)
		(eats cherry arugula)
		(eats scallop grapefruit)
		(eats scallion muffin)
		(= (locale muffin) 4.0)
		(= (locale shrimp) 2.0)
		(eats muffin cherry)
	)
	(:goal
			(and
				(craves sciatica wurst)
			)
	)
)