(define (problem roverprob1425)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 rover2 rover3 - rover
		rover0store rover1store rover2store rover3store - store
		waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 waypoint7 waypoint8 waypoint9 - waypoint
		camera0 camera1 camera2 camera3 camera4 - camera
		objective0 objective1 objective2 objective3 - objective
	)
	(:init
		(visible waypoint0 waypoint9)
		(in_sun waypoint5)
		(can_traverse rover3 waypoint2 waypoint6)
		(visible waypoint9 waypoint2)
		(= (energy rover1) 50.0)
		(visible waypoint5 waypoint6)
		(supports camera0 colour)
		(can_traverse rover3 waypoint6 waypoint2)
		(= (energy rover0) 50.0)
		(can_traverse rover1 waypoint4 waypoint5)
		(can_traverse rover2 waypoint3 waypoint2)
		(visible_from objective0 waypoint1)
		(visible waypoint8 waypoint9)
		(supports camera2 low_res)
		(visible waypoint5 waypoint1)
		(visible_from objective1 waypoint5)
		(visible waypoint4 waypoint1)
		(visible waypoint4 waypoint6)
		(visible waypoint6 waypoint4)
		(on_board camera1 rover2)
		(empty rover1store)
		(can_traverse rover0 waypoint4 waypoint5)
		(visible waypoint1 waypoint4)
		(on_board camera2 rover1)
		(visible_from objective0 waypoint0)
		(available rover0)
		(visible waypoint7 waypoint5)
		(can_traverse rover1 waypoint4 waypoint2)
		(can_traverse rover1 waypoint1 waypoint2)
		(visible_from objective1 waypoint0)
		(visible_from objective2 waypoint1)
		(on_board camera4 rover0)
		(visible waypoint2 waypoint9)
		(visible_from objective1 waypoint4)
		(visible waypoint8 waypoint1)
		(visible waypoint3 waypoint2)
		(can_traverse rover2 waypoint4 waypoint0)
		(can_traverse rover1 waypoint3 waypoint0)
		(can_traverse rover3 waypoint6 waypoint8)
		(can_traverse rover3 waypoint1 waypoint7)
		(supports camera3 colour)
		(visible_from objective3 waypoint0)
		(= (energy rover2) 50.0)
		(visible waypoint5 waypoint4)
		(visible_from objective2 waypoint4)
		(visible waypoint9 waypoint6)
		(available rover3)
		(store_of rover0store rover0)
		(visible_from objective2 waypoint5)
		(can_traverse rover1 waypoint5 waypoint4)
		(can_traverse rover0 waypoint8 waypoint1)
		(can_traverse rover2 waypoint4 waypoint1)
		(store_of rover1store rover1)
		(visible_from objective1 waypoint2)
	)
	(:goal
			(and
				(communicated_soil_data waypoint3)
				(communicated_soil_data waypoint6)
				(communicated_rock_data waypoint5)
				(communicated_rock_data waypoint4)
				(communicated_rock_data waypoint8)
				(communicated_image_data objective0 colour)
				(communicated_image_data objective2 low_res)
				(communicated_image_data objective0 low_res)
			)
	)
)