(define (problem mprime-x-19)
	(:domain mystery-prime-typed)
	(:objects
		bacon tofu lamb lobster beef cantelope onion wonderbread lemon haroset marzipan flounder okra snickers ham - food
		aesthetics stimulation entertainment achievement lubricity love expectation learning - pleasure
		sciatica loneliness laceration grief abrasion anxiety dread boils jealousy prostatitis anger hangover depression angina - pain
	)
	(:init
		(= (locale haroset) 1.0)
		(craves expectation okra)
		(craves aesthetics bacon)
		(eats ham flounder)
		(eats lemon beef)
		(= (locale lobster) 1.0)
		(craves lubricity lemon)
		(eats lamb beef)
		(eats bacon wonderbread)
		(= (harmony achievement) 2.0)
		(= (locale onion) 0.0)
		(eats beef lemon)
		(eats okra snickers)
		(eats haroset lobster)
		(= (locale flounder) 3.0)
		(eats onion snickers)
		(craves stimulation lamb)
		(= (harmony love) 1.0)
		(craves abrasion beef)
		(craves angina ham)
		(eats marzipan cantelope)
		(craves entertainment lobster)
		(eats onion tofu)
		(craves achievement wonderbread)
		(eats lobster bacon)
		(eats lemon ham)
		(= (locale lamb) 5.0)
		(= (locale lemon) 1.0)
		(= (harmony lubricity) 3.0)
		(eats wonderbread marzipan)
		(eats wonderbread bacon)
		(eats okra wonderbread)
		(= (locale wonderbread) 0.0)
		(= (locale beef) 3.0)
		(craves hangover okra)
		(= (locale tofu) 1.0)
		(eats lemon cantelope)
		(craves sciatica bacon)
		(craves depression snickers)
		(craves boils lemon)
		(eats beef lamb)
		(eats tofu marzipan)
		(eats tofu onion)
		(= (locale snickers) 1.0)
		(craves learning snickers)
		(craves prostatitis marzipan)
		(eats flounder ham)
		(eats ham lemon)
		(craves jealousy haroset)
		(eats marzipan tofu)
		(craves grief lobster)
		(eats wonderbread okra)
		(eats snickers okra)
		(craves laceration lamb)
		(eats lobster haroset)
		(= (harmony aesthetics) 3.0)
		(eats haroset lamb)
		(eats beef marzipan)
		(= (harmony learning) 2.0)
		(eats wonderbread snickers)
		(= (harmony entertainment) 1.0)
		(= (locale okra) 1.0)
		(= (harmony stimulation) 3.0)
		(eats flounder haroset)
		(eats marzipan beef)
		(eats haroset flounder)
		(= (locale bacon) 1.0)
		(= (locale marzipan) 3.0)
		(craves anxiety onion)
		(craves love haroset)
		(eats marzipan wonderbread)
		(craves anger flounder)
		(eats cantelope lemon)
		(eats lamb haroset)
		(= (locale cantelope) 0.0)
		(eats snickers wonderbread)
		(craves loneliness tofu)
		(eats cantelope marzipan)
		(= (locale ham) 5.0)
		(eats snickers onion)
		(= (harmony expectation) 2.0)
		(eats bacon lobster)
		(craves dread wonderbread)
	)
	(:goal
			(and
				(craves abrasion lobster)
			)
	)
)