(define (problem mprime-x-19)
	(:domain mystery-prime-typed)
	(:objects
		bacon tofu lamb lobster beef cantelope onion wonderbread lemon haroset marzipan flounder okra snickers ham - food
		aesthetics stimulation entertainment achievement lubricity love expectation learning - pleasure
		sciatica loneliness laceration grief abrasion anxiety dread boils jealousy prostatitis anger hangover depression angina - pain
	)
	(:init
		(eats snickers wonderbread)
		(eats flounder haroset)
		(eats lamb haroset)
		(craves stimulation lamb)
		(craves depression snickers)
		(= (harmony stimulation) 3.0)
		(craves angina ham)
		(= (locale onion) 0.0)
		(eats haroset flounder)
		(eats marzipan beef)
		(eats ham flounder)
		(eats marzipan cantelope)
		(= (locale lobster) 1.0)
		(= (harmony lubricity) 3.0)
		(= (locale lemon) 1.0)
		(= (harmony achievement) 2.0)
		(= (locale tofu) 1.0)
		(= (locale beef) 3.0)
		(eats tofu onion)
		(eats lemon cantelope)
		(= (locale cantelope) 0.0)
		(eats snickers onion)
		(= (harmony entertainment) 1.0)
		(eats lamb beef)
		(craves learning snickers)
		(eats wonderbread marzipan)
		(craves love haroset)
		(craves entertainment lobster)
		(eats okra snickers)
		(= (locale bacon) 1.0)
		(eats cantelope marzipan)
		(craves loneliness tofu)
		(eats haroset lamb)
		(= (locale haroset) 1.0)
		(craves hangover okra)
		(= (locale flounder) 3.0)
		(craves achievement wonderbread)
		(eats bacon wonderbread)
		(eats snickers okra)
		(= (locale okra) 1.0)
		(= (harmony aesthetics) 3.0)
	)
	(:goal
			(and
				(craves abrasion lobster)
			)
	)
)