(define (problem mprime-x-19)
	(:domain mystery-prime-typed)
	(:objects
		bacon tofu lamb lobster beef cantelope onion wonderbread lemon haroset marzipan flounder okra snickers ham - food
		aesthetics stimulation entertainment achievement lubricity love expectation learning - pleasure
		sciatica loneliness laceration grief abrasion anxiety dread boils jealousy prostatitis anger hangover depression angina - pain
	)
	(:init
		(eats bacon lobster)
		(eats marzipan tofu)
		(eats wonderbread marzipan)
		(= (harmony stimulation) 3.0)
		(craves anger flounder)
		(eats lemon beef)
		(= (harmony love) 1.0)
		(= (locale bacon) 1.0)
		(craves stimulation lamb)
		(= (locale beef) 3.0)
		(eats lobster haroset)
		(craves angina ham)
		(eats snickers wonderbread)
		(craves prostatitis marzipan)
		(eats marzipan beef)
		(= (locale onion) 0.0)
		(= (locale lobster) 1.0)
		(= (locale cantelope) 0.0)
		(craves grief lobster)
		(craves boils lemon)
		(craves anxiety onion)
		(craves aesthetics bacon)
		(= (harmony aesthetics) 3.0)
		(eats flounder haroset)
		(eats lemon ham)
		(craves dread wonderbread)
		(= (harmony achievement) 2.0)
		(eats beef lemon)
		(eats okra wonderbread)
		(= (locale ham) 5.0)
		(eats wonderbread snickers)
		(craves learning snickers)
		(eats onion tofu)
		(craves jealousy haroset)
		(eats ham lemon)
		(craves love haroset)
		(eats haroset flounder)
		(eats lemon cantelope)
		(= (locale snickers) 1.0)
		(craves entertainment lobster)
		(eats marzipan cantelope)
		(eats tofu marzipan)
		(eats marzipan wonderbread)
		(= (locale lamb) 5.0)
		(= (locale okra) 1.0)
		(eats snickers onion)
		(eats tofu onion)
		(eats okra snickers)
		(eats lamb beef)
		(craves expectation okra)
		(= (locale haroset) 1.0)
		(= (harmony entertainment) 1.0)
		(craves hangover okra)
		(eats beef lamb)
		(eats beef marzipan)
		(eats ham flounder)
		(= (harmony expectation) 2.0)
		(eats bacon wonderbread)
		(eats flounder ham)
		(craves loneliness tofu)
		(= (harmony lubricity) 3.0)
		(eats cantelope lemon)
	)
	(:goal
			(and
				(craves abrasion lobster)
			)
	)
)