(define (problem delivery-x-11-octopus)
	(:domain delivery)
	(:objects
		rooma roomb - room
		item24 item23 item22 item21 item20 item19 item18 item17 item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		octopus - bot
		t1 t2 t3 t4 t5 t6 t7 t8 - arm
	)
	(:init
		(= (weight item1) 1.0)
		(= (weight item12) 1.0)
		(= (cost) 0.0)
		(at item3 rooma)
		(= (weight item17) 1.0)
		(at item12 rooma)
		(= (weight item15) 1.0)
		(= (weight item4) 1.0)
		(mount t7 octopus)
		(at item14 rooma)
		(at item2 rooma)
		(at item21 rooma)
		(= (weight item18) 1.0)
		(= (weight item10) 1.0)
		(at item9 rooma)
		(mount t4 octopus)
		(= (weight item2) 1.0)
		(= (weight item11) 1.0)
		(at item15 rooma)
		(= (weight item22) 1.0)
		(= (weight item3) 1.0)
		(= (current_load octopus) 0.0)
		(= (load_limit octopus) 8.0)
		(free t3)
		(at item16 rooma)
		(at item11 rooma)
		(at item18 rooma)
		(free t6)
		(mount t2 octopus)
		(door rooma roomb)
		(= (weight item19) 1.0)
		(at-bot octopus rooma)
		(at item24 rooma)
		(free t4)
		(free t8)
		(at item8 rooma)
		(at item22 rooma)
		(at item23 rooma)
		(door roomb rooma)
		(= (weight item23) 1.0)
		(at item7 rooma)
		(free t1)
		(mount t6 octopus)
		(mount t1 octopus)
		(= (weight item7) 1.0)
		(at item20 rooma)
		(= (weight item13) 1.0)
		(at item17 rooma)
		(= (weight item5) 1.0)
		(free t7)
		(= (weight item9) 1.0)
		(= (weight item21) 1.0)
		(= (weight item6) 1.0)
		(at item4 rooma)
		(at item6 rooma)
		(mount t5 octopus)
		(at item1 rooma)
		(mount t8 octopus)
		(= (weight item16) 1.0)
		(free t2)
		(= (weight item14) 1.0)
		(mount t3 octopus)
		(free t5)
		(= (weight item8) 1.0)
		(at item10 rooma)
		(at item5 rooma)
		(at item13 rooma)
		(= (weight item24) 1.0)
		(at item19 rooma)
		(= (weight item20) 1.0)
	)
	(:goal
			(and
				(at item24 roomb)
				(at item23 roomb)
				(at item22 roomb)
				(at item21 roomb)
				(at item20 roomb)
				(at item19 roomb)
				(at item18 roomb)
				(at item17 roomb)
				(at item16 roomb)
				(at item15 roomb)
				(at item14 roomb)
				(at item13 roomb)
				(at item12 roomb)
				(at item11 roomb)
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomb)
				(at item7 roomb)
				(at item6 roomb)
				(at item5 roomb)
				(at item4 roomb)
				(at item3 roomb)
				(at item2 roomb)
				(at item1 roomb)
			)
	)
)