(define (problem delivery-x-6)
	(:domain delivery)
	(:objects
		rooma roomb roomc roomd - room
		item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(= (load_limit bot2) 6.0)
		(= (weight item11) 1.0)
		(free right1)
		(door roomb roomd)
		(= (load_limit bot1) 6.0)
		(= (weight item12) 1.0)
		(= (weight item9) 1.0)
		(at item5 rooma)
		(= (weight item10) 1.0)
		(at item7 rooma)
		(at-bot bot2 rooma)
		(= (weight item5) 1.0)
		(door roomc rooma)
		(at item4 rooma)
		(= (weight item14) 2.0)
		(at item8 rooma)
		(mount left2 bot2)
		(= (weight item4) 1.0)
		(at item9 rooma)
		(door rooma roomc)
		(free left2)
		(= (weight item3) 1.0)
		(= (weight item13) 2.0)
		(mount left1 bot1)
		(= (cost) 0.0)
	)
	(:goal
			(and
				(at item14 roomd)
				(at item13 roomd)
				(at item12 roomb)
				(at item11 roomb)
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomb)
				(at item7 roomd)
				(at item6 roomd)
				(at item5 roomc)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)