(define (problem delivery-x-6)
	(:domain delivery)
	(:objects
		rooma roomb roomc roomd - room
		item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(= (cost) 0.0)
		(at item1 rooma)
		(at item3 rooma)
		(= (weight item4) 1.0)
		(= (weight item6) 2.0)
		(mount right2 bot2)
		(at item4 rooma)
		(= (weight item8) 1.0)
		(free right2)
		(at item8 rooma)
		(= (weight item10) 1.0)
		(= (load_limit bot2) 6.0)
		(= (weight item12) 1.0)
		(mount left1 bot1)
		(at-bot bot1 rooma)
		(= (weight item5) 1.0)
		(= (weight item14) 2.0)
		(door roomc rooma)
		(door roomb roomd)
		(door roomd roomb)
		(door roomb rooma)
		(= (weight item11) 1.0)
		(free right1)
		(at item12 rooma)
		(door rooma roomb)
		(= (weight item13) 2.0)
		(= (current_load bot1) 0.0)
		(at item14 rooma)
		(= (weight item7) 2.0)
		(free left1)
		(at-bot bot2 rooma)
		(= (weight item2) 1.0)
		(= (weight item3) 1.0)
		(at item5 rooma)
		(free left2)
		(at item11 rooma)
		(at item7 rooma)
		(at item10 rooma)
	)
	(:goal
			(and
				(at item14 roomd)
				(at item13 roomd)
				(at item12 roomb)
				(at item11 roomb)
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomb)
				(at item7 roomd)
				(at item6 roomd)
				(at item5 roomc)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)