(define (problem roverprob6232)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 - rover
		rover0store rover1store - store
		waypoint0 waypoint1 waypoint2 waypoint3 - waypoint
		camera0 camera1 camera2 - camera
		objective0 objective1 objective2 - objective
	)
	(:init
		(on_board camera0 rover1)
		(visible waypoint0 waypoint1)
		(can_traverse rover1 waypoint0 waypoint1)
		(supports camera1 low_res)
		(visible waypoint3 waypoint1)
		(store_of rover1store rover1)
		(at_lander general waypoint2)
		(= (energy rover1) 50.0)
		(visible waypoint1 waypoint2)
		(on_board camera2 rover0)
		(visible waypoint3 waypoint2)
		(can_traverse rover1 waypoint2 waypoint1)
		(can_traverse rover1 waypoint1 waypoint0)
		(can_traverse rover0 waypoint1 waypoint3)
		(visible_from objective2 waypoint2)
		(equipped_for_imaging rover0)
		(visible waypoint1 waypoint3)
		(store_of rover0store rover0)
		(can_traverse rover1 waypoint1 waypoint2)
		(in rover0 waypoint3)
		(visible waypoint2 waypoint1)
		(equipped_for_soil_analysis rover0)
		(calibration_target camera2 objective1)
		(visible_from objective0 waypoint1)
		(calibration_target camera1 objective0)
		(equipped_for_soil_analysis rover1)
		(can_traverse rover1 waypoint2 waypoint3)
		(on_board camera1 rover0)
		(channel_free general)
		(available rover1)
		(visible waypoint2 waypoint3)
		(supports camera0 high_res)
		(calibration_target camera0 objective0)
		(= (recharges) 0.0)
		(visible waypoint1 waypoint0)
		(visible_from objective2 waypoint1)
		(visible_from objective1 waypoint0)
		(visible_from objective0 waypoint3)
		(in rover1 waypoint2)
		(supports camera2 low_res)
		(supports camera0 colour)
		(can_traverse rover0 waypoint3 waypoint1)
		(visible_from objective0 waypoint2)
		(equipped_for_rock_analysis rover1)
		(can_traverse rover1 waypoint3 waypoint2)
	)
	(:goal
			(and
				(communicated_soil_data waypoint3)
				(communicated_rock_data waypoint1)
				(communicated_image_data objective0 high_res)
			)
	)
)