(define (problem mprime-x-16)
	(:domain mystery-prime-typed)
	(:objects
		chicken pepper guava marzipan bacon arugula flounder wonderbread baguette rice chocolate - food
		rest stimulation excitement satiety learning achievement triumph - pleasure
		prostatitis boils loneliness depression angina jealousy abrasion sciatica grief - pain
	)
	(:init
		(= (harmony excitement) 3.0)
		(= (locale rice) 1.0)
		(eats baguette guava)
		(= (locale flounder) 1.0)
		(= (locale pepper) 3.0)
		(eats chicken marzipan)
		(eats guava baguette)
		(= (locale arugula) 3.0)
		(craves prostatitis chicken)
		(= (locale guava) 4.0)
		(eats rice baguette)
		(eats marzipan chicken)
		(craves grief baguette)
		(eats flounder wonderbread)
		(eats pepper guava)
		(craves depression bacon)
		(craves excitement arugula)
		(eats baguette arugula)
		(= (locale marzipan) 0.0)
		(eats bacon chicken)
		(eats marzipan chocolate)
		(eats chocolate flounder)
		(= (locale baguette) 0.0)
		(eats chocolate pepper)
		(craves achievement rice)
		(= (harmony stimulation) 3.0)
		(= (harmony triumph) 2.0)
		(eats wonderbread arugula)
		(craves triumph chocolate)
		(craves learning baguette)
		(eats arugula wonderbread)
		(eats rice bacon)
		(craves jealousy wonderbread)
		(craves stimulation pepper)
		(craves boils pepper)
		(eats baguette rice)
		(= (locale wonderbread) 2.0)
		(craves rest chicken)
		(eats bacon rice)
		(= (harmony rest) 1.0)
		(= (locale bacon) 4.0)
		(craves abrasion baguette)
		(= (locale chicken) 0.0)
		(= (locale chocolate) 5.0)
		(eats pepper chocolate)
		(craves angina wonderbread)
		(eats wonderbread flounder)
		(craves sciatica baguette)
		(eats flounder chocolate)
		(craves loneliness bacon)
		(eats guava pepper)
		(= (harmony achievement) 2.0)
		(eats arugula baguette)
		(eats chicken bacon)
		(= (harmony learning) 2.0)
		(craves satiety wonderbread)
		(eats chocolate marzipan)
		(= (harmony satiety) 1.0)
	)
	(:goal
			(and
				(craves abrasion rice)
				(craves sciatica rice)
			)
	)
)