(define (problem mprime-x-16)
	(:domain mystery-prime-typed)
	(:objects
		chicken pepper guava marzipan bacon arugula flounder wonderbread baguette rice chocolate - food
		rest stimulation excitement satiety learning achievement triumph - pleasure
		prostatitis boils loneliness depression angina jealousy abrasion sciatica grief - pain
	)
	(:init
		(eats chocolate flounder)
		(craves rest chicken)
		(eats flounder wonderbread)
		(eats baguette arugula)
		(eats guava pepper)
		(= (locale bacon) 4.0)
		(eats arugula baguette)
		(eats rice baguette)
		(= (harmony stimulation) 3.0)
		(craves stimulation pepper)
		(craves jealousy wonderbread)
		(= (locale guava) 4.0)
		(= (locale rice) 1.0)
		(eats chicken marzipan)
		(= (harmony rest) 1.0)
		(craves satiety wonderbread)
		(eats pepper guava)
		(eats wonderbread flounder)
		(craves loneliness bacon)
		(= (harmony achievement) 2.0)
		(eats marzipan chocolate)
		(craves triumph chocolate)
		(craves sciatica baguette)
		(eats pepper chocolate)
		(= (harmony triumph) 2.0)
		(craves learning baguette)
		(craves grief baguette)
		(= (locale flounder) 1.0)
		(= (locale pepper) 3.0)
	)
	(:goal
			(and
				(craves abrasion rice)
				(craves sciatica rice)
			)
	)
)