(define (problem roverprob8271)
	(:domain rover)
	(:objects
		general - lander
		colour high_res low_res - mode
		rover0 rover1 rover2 rover3 - rover
		rover0store rover1store rover2store rover3store - store
		waypoint0 waypoint1 waypoint2 waypoint3 waypoint4 waypoint5 waypoint6 - waypoint
		camera0 camera1 camera2 camera3 camera4 camera5 - camera
		objective0 objective1 objective2 objective3 - objective
	)
	(:init
		(at_rock_sample waypoint6)
		(empty rover2store)
		(equipped_for_imaging rover3)
		(supports camera0 low_res)
		(channel_free general)
		(can_traverse rover0 waypoint6 waypoint4)
		(can_traverse rover2 waypoint5 waypoint3)
		(visible waypoint5 waypoint1)
		(visible_from objective1 waypoint1)
		(can_traverse rover3 waypoint2 waypoint0)
		(can_traverse rover2 waypoint3 waypoint4)
		(can_traverse rover3 waypoint0 waypoint4)
		(can_traverse rover0 waypoint5 waypoint1)
		(supports camera5 low_res)
		(can_traverse rover2 waypoint4 waypoint1)
		(visible waypoint4 waypoint6)
		(on_board camera2 rover1)
		(supports camera4 colour)
		(visible waypoint6 waypoint4)
		(can_traverse rover0 waypoint3 waypoint4)
		(visible waypoint5 waypoint0)
		(empty rover1store)
		(visible waypoint4 waypoint3)
		(can_traverse rover1 waypoint6 waypoint0)
		(visible waypoint1 waypoint5)
		(can_traverse rover0 waypoint4 waypoint6)
		(on_board camera1 rover1)
		(at_soil_sample waypoint6)
		(available rover0)
		(available rover2)
		(supports camera3 high_res)
		(visible_from objective2 waypoint3)
		(can_traverse rover3 waypoint0 waypoint2)
		(store_of rover2store rover2)
		(visible waypoint1 waypoint0)
		(calibration_target camera3 objective2)
		(visible_from objective1 waypoint0)
	)
	(:goal
			(and
				(communicated_soil_data waypoint6)
				(communicated_soil_data waypoint0)
				(communicated_soil_data waypoint3)
				(communicated_soil_data waypoint4)
				(communicated_rock_data waypoint4)
				(communicated_rock_data waypoint3)
				(communicated_rock_data waypoint0)
				(communicated_rock_data waypoint1)
				(communicated_image_data objective3 colour)
				(communicated_image_data objective2 colour)
				(communicated_image_data objective3 low_res)
			)
	)
)