(define (problem mprime-x-27)
	(:domain mystery-prime-typed)
	(:objects
		wurst guava muffin pork onion popover scallion - food
		triumph love satisfaction - pleasure
		abrasion anxiety dread loneliness grief boils - pain
	)
	(:init
		(craves dread wurst)
		(eats pork onion)
		(eats scallion muffin)
		(eats guava scallion)
		(eats wurst guava)
		(craves satisfaction scallion)
		(= (locale popover) 9.0)
		(= (locale guava) 9.0)
		(= (locale pork) 5.0)
		(eats onion muffin)
		(craves abrasion wurst)
		(eats scallion popover)
		(= (harmony satisfaction) 2.0)
		(craves anxiety wurst)
		(eats muffin onion)
		(= (locale onion) 12.0)
		(= (harmony triumph) 3.0)
		(eats popover scallion)
		(eats guava wurst)
		(craves loneliness scallion)
		(craves grief scallion)
		(eats muffin scallion)
		(eats onion pork)
		(eats onion popover)
		(= (locale muffin) 2.0)
		(= (harmony love) 2.0)
		(eats muffin pork)
		(craves triumph onion)
		(eats scallion guava)
		(eats wurst onion)
		(eats pork muffin)
		(eats onion wurst)
		(eats popover onion)
		(craves boils scallion)
		(= (locale scallion) 5.0)
		(= (locale wurst) 10.0)
		(craves love popover)
	)
	(:goal
			(and
				(craves grief guava)
				(craves boils guava)
			)
	)
)