(define (problem mprime-x-23)
	(:domain mystery-prime-typed)
	(:objects
		flounder okra ham papaya cherry scallop pistachio lamb sweetroll apple onion haroset lobster chicken beef grapefruit hotdog wonderbread bacon - food
		learning understanding satisfaction intoxication empathy curiosity triumph - pleasure
		sciatica boils abrasion angina anger anxiety loneliness hangover laceration jealousy depression prostatitis grief dread boils-2 anxiety-1 - pain
	)
	(:init
		(craves anxiety scallop)
		(craves grief chicken)
		(craves boils okra)
		(eats grapefruit hotdog)
		(craves angina papaya)
		(eats wonderbread bacon)
		(eats apple onion)
		(eats okra lamb)
		(craves laceration apple)
		(craves sciatica flounder)
		(craves anger cherry)
		(eats hotdog chicken)
		(eats papaya ham)
		(eats hotdog grapefruit)
		(= (locale papaya) 3.0)
		(eats hotdog lamb)
		(craves understanding cherry)
		(= (harmony understanding) 2.0)
		(eats bacon wonderbread)
		(eats pistachio scallop)
		(= (locale cherry) 3.0)
		(= (locale pistachio) 4.0)
		(eats sweetroll okra)
		(eats pistachio cherry)
		(eats onion apple)
		(= (locale wonderbread) 2.0)
		(eats lamb flounder)
		(eats cherry pistachio)
		(= (harmony satisfaction) 2.0)
		(= (locale hotdog) 0.0)
		(= (harmony learning) 1.0)
		(eats lamb papaya)
		(= (locale apple) 4.0)
		(eats beef lobster)
		(eats lamb okra)
		(craves abrasion ham)
		(craves satisfaction lamb)
		(eats ham papaya)
		(craves jealousy onion)
		(eats pistachio apple)
		(= (locale lamb) 3.0)
		(craves anxiety-1 wonderbread)
		(= (locale lobster) 2.0)
		(eats grapefruit haroset)
		(eats bacon lobster)
		(eats chicken beef)
		(eats ham scallop)
		(craves intoxication onion)
		(= (locale ham) 5.0)
		(eats papaya lamb)
		(eats pistachio onion)
		(eats lobster beef)
		(eats apple pistachio)
		(eats bacon haroset)
		(craves prostatitis lobster)
		(= (locale bacon) 4.0)
		(= (locale beef) 1.0)
		(eats beef grapefruit)
		(craves depression haroset)
		(eats flounder onion)
		(eats okra sweetroll)
		(craves empathy haroset)
		(eats chicken hotdog)
		(= (harmony empathy) 1.0)
		(= (locale flounder) 4.0)
		(craves triumph bacon)
		(= (harmony curiosity) 2.0)
		(eats beef chicken)
		(eats scallop pistachio)
		(eats hotdog wonderbread)
		(= (locale grapefruit) 1.0)
		(= (locale onion) 1.0)
	)
	(:goal
			(and
				(craves laceration chicken)
			)
	)
)