(define (problem mprime-x-23)
	(:domain mystery-prime-typed)
	(:objects
		flounder okra ham papaya cherry scallop pistachio lamb sweetroll apple onion haroset lobster chicken beef grapefruit hotdog wonderbread bacon - food
		learning understanding satisfaction intoxication empathy curiosity triumph - pleasure
		sciatica boils abrasion angina anger anxiety loneliness hangover laceration jealousy depression prostatitis grief dread boils-2 anxiety-1 - pain
	)
	(:init
		(craves prostatitis lobster)
		(eats grapefruit haroset)
		(craves hangover sweetroll)
		(= (harmony satisfaction) 2.0)
		(eats grapefruit beef)
		(= (locale apple) 4.0)
		(eats beef chicken)
		(= (harmony intoxication) 2.0)
		(eats chicken hotdog)
		(craves anxiety-1 wonderbread)
		(= (locale lamb) 3.0)
		(eats flounder lamb)
		(= (harmony understanding) 2.0)
		(= (locale onion) 1.0)
		(eats pistachio scallop)
		(eats bacon wonderbread)
		(craves depression haroset)
		(eats lamb okra)
		(eats sweetroll okra)
		(eats onion flounder)
		(eats pistachio apple)
		(craves curiosity grapefruit)
		(= (locale beef) 1.0)
		(craves laceration apple)
		(craves sciatica flounder)
		(eats flounder onion)
		(craves dread beef)
		(eats onion apple)
		(eats beef grapefruit)
		(= (harmony curiosity) 2.0)
		(eats chicken beef)
		(eats ham papaya)
		(eats ham scallop)
		(= (locale pistachio) 4.0)
		(eats haroset bacon)
		(eats apple pistachio)
		(eats hotdog lamb)
		(= (harmony learning) 1.0)
		(eats apple onion)
		(= (locale papaya) 3.0)
		(eats lobster bacon)
		(= (locale chicken) 4.0)
		(= (locale sweetroll) 0.0)
		(eats wonderbread hotdog)
		(= (locale wonderbread) 2.0)
		(= (locale haroset) 4.0)
		(= (locale okra) 1.0)
		(eats onion pistachio)
	)
	(:goal
			(and
				(craves laceration chicken)
			)
	)
)