(define (problem mprime-x-23)
	(:domain mystery-prime-typed)
	(:objects
		flounder okra ham papaya cherry scallop pistachio lamb sweetroll apple onion haroset lobster chicken beef grapefruit hotdog wonderbread bacon - food
		learning understanding satisfaction intoxication empathy curiosity triumph - pleasure
		sciatica boils abrasion angina anger anxiety loneliness hangover laceration jealousy depression prostatitis grief dread boils-2 anxiety-1 - pain
	)
	(:init
		(eats scallop ham)
		(craves angina papaya)
		(craves anxiety scallop)
		(= (harmony intoxication) 2.0)
		(eats papaya ham)
		(craves abrasion ham)
		(craves depression haroset)
		(eats cherry pistachio)
		(eats sweetroll cherry)
		(craves learning okra)
		(eats bacon lobster)
		(craves boils okra)
		(eats apple onion)
		(= (locale okra) 1.0)
		(eats beef grapefruit)
		(eats hotdog lamb)
		(eats hotdog grapefruit)
		(= (harmony learning) 1.0)
		(eats bacon wonderbread)
		(eats hotdog wonderbread)
		(eats ham scallop)
		(craves jealousy onion)
		(eats okra lamb)
		(eats pistachio cherry)
		(= (harmony empathy) 1.0)
		(eats lamb okra)
		(eats onion pistachio)
		(= (locale onion) 1.0)
		(craves laceration apple)
		(= (locale ham) 5.0)
		(eats ham papaya)
		(craves boils-2 grapefruit)
		(eats flounder lamb)
		(eats papaya lamb)
		(eats chicken beef)
		(= (harmony curiosity) 2.0)
		(eats wonderbread hotdog)
		(eats okra sweetroll)
		(craves sciatica flounder)
		(= (locale scallop) 5.0)
		(= (locale beef) 1.0)
		(eats bacon haroset)
		(craves anger cherry)
		(eats beef chicken)
		(craves hangover sweetroll)
		(= (harmony understanding) 2.0)
		(eats beef lobster)
		(= (locale lamb) 3.0)
		(= (locale papaya) 3.0)
		(eats apple pistachio)
		(= (locale haroset) 4.0)
		(eats flounder onion)
		(eats haroset bacon)
		(eats cherry sweetroll)
		(eats grapefruit hotdog)
		(= (locale wonderbread) 2.0)
		(craves understanding cherry)
		(= (locale apple) 4.0)
		(craves loneliness pistachio)
		(= (locale chicken) 4.0)
		(eats lobster bacon)
		(eats grapefruit haroset)
		(craves triumph bacon)
		(eats pistachio scallop)
		(craves intoxication onion)
		(craves empathy haroset)
		(= (harmony satisfaction) 2.0)
		(eats pistachio onion)
		(= (locale lobster) 2.0)
		(craves curiosity grapefruit)
		(eats scallop pistachio)
		(= (harmony triumph) 3.0)
		(eats sweetroll okra)
		(= (locale bacon) 4.0)
		(eats lamb flounder)
		(eats onion flounder)
		(eats pistachio apple)
		(= (locale hotdog) 0.0)
		(eats haroset grapefruit)
		(eats grapefruit beef)
		(eats lamb hotdog)
		(eats hotdog chicken)
		(craves dread beef)
		(craves grief chicken)
		(= (locale pistachio) 4.0)
		(eats lamb papaya)
		(eats wonderbread bacon)
		(eats lobster beef)
		(= (locale cherry) 3.0)
		(= (locale grapefruit) 1.0)
		(= (locale flounder) 4.0)
		(= (locale sweetroll) 0.0)
		(eats chicken hotdog)
		(eats onion apple)
		(craves prostatitis lobster)
		(craves satisfaction lamb)
		(craves anxiety-1 wonderbread)
	)
	(:goal
			(and
				(craves laceration chicken)
			)
	)
)