(define (problem delivery-x-8)
	(:domain delivery)
	(:objects
		rooma roomb roomc roomd - room
		item18 item17 item16 item15 item14 item13 item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(free right2)
		(at item12 rooma)
		(at item16 rooma)
		(= (weight item15) 1.0)
		(door rooma roomc)
		(at item5 rooma)
		(at item6 rooma)
		(= (weight item16) 1.0)
		(at item15 rooma)
		(mount left1 bot1)
		(= (cost) 0.0)
		(at item3 rooma)
		(free right1)
		(free left1)
		(at item18 rooma)
		(= (weight item8) 1.0)
		(= (weight item9) 1.0)
		(at item1 rooma)
		(at item11 rooma)
		(at item13 rooma)
		(door rooma roomb)
		(at item7 rooma)
		(= (weight item18) 1.0)
		(at-bot bot1 rooma)
		(= (current_load bot1) 0.0)
		(mount right2 bot2)
		(= (weight item17) 1.0)
		(= (weight item11) 1.0)
		(= (weight item3) 1.0)
		(= (weight item14) 1.0)
		(free left2)
		(= (load_limit bot1) 6.0)
		(at item9 rooma)
		(mount right1 bot1)
		(door roomd roomc)
		(= (weight item12) 1.0)
		(at item2 rooma)
		(= (weight item1) 1.0)
		(= (weight item13) 1.0)
		(at item17 rooma)
		(at item4 rooma)
		(mount left2 bot2)
		(= (weight item6) 1.0)
		(at-bot bot2 rooma)
	)
	(:goal
			(and
				(at item18 roomd)
				(at item17 roomd)
				(at item16 roomd)
				(at item15 roomd)
				(at item14 roomd)
				(at item13 roomd)
				(at item12 roomc)
				(at item11 roomc)
				(at item10 roomc)
				(at item9 roomc)
				(at item8 roomc)
				(at item7 roomc)
				(at item6 roomb)
				(at item5 roomb)
				(at item4 roomb)
				(at item3 roomb)
				(at item2 roomb)
				(at item1 roomb)
			)
	)
)