(define (problem delivery-x-4)
	(:domain delivery)
	(:objects
		rooma roomb roomc roomd - room
		item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(= (load_limit bot2) 4.0)
		(= (weight item5) 1.0)
		(at item6 rooma)
		(at-bot bot1 rooma)
		(door roomb rooma)
		(at item5 rooma)
		(mount right1 bot1)
		(= (weight item8) 1.0)
		(= (current_load bot1) 0.0)
		(= (weight item6) 1.0)
		(at item7 rooma)
		(at item3 rooma)
		(free left2)
		(= (weight item10) 2.0)
		(= (weight item2) 1.0)
		(mount right2 bot2)
		(at item10 rooma)
		(mount left1 bot1)
		(at-bot bot2 rooma)
		(door rooma roomc)
		(at item1 rooma)
		(= (current_load bot2) 0.0)
		(at item9 rooma)
		(= (weight item7) 1.0)
		(= (weight item4) 1.0)
		(door roomb roomd)
		(at item4 rooma)
		(= (weight item9) 2.0)
		(= (weight item3) 1.0)
		(= (cost) 0.0)
		(at item2 rooma)
		(mount left2 bot2)
		(door roomd roomb)
		(= (weight item1) 1.0)
		(at item8 rooma)
		(door roomc rooma)
		(door rooma roomb)
		(= (load_limit bot1) 4.0)
		(free left1)
		(free right2)
		(free right1)
	)
	(:goal
			(and
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomd)
				(at item7 roomd)
				(at item6 roomd)
				(at item5 roomd)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)