(define (problem delivery-x-4)
	(:domain delivery)
	(:objects
		rooma roomb roomc roomd - room
		item12 item11 item10 item9 item8 item7 item6 item5 item4 item3 item2 item1 - item
		bot1 bot2 - bot
		left1 right1 left2 right2 - arm
	)
	(:init
		(at-bot bot2 rooma)
		(free left2)
		(= (current_load bot2) 0.0)
		(at item5 rooma)
		(at item6 rooma)
		(= (weight item7) 1.0)
		(door rooma roomc)
		(door roomb roomd)
		(at-bot bot1 rooma)
		(free left1)
		(at item10 rooma)
		(= (weight item2) 1.0)
		(= (weight item1) 1.0)
		(= (load_limit bot1) 4.0)
		(= (cost) 0.0)
		(at item1 rooma)
		(mount right2 bot2)
		(= (weight item4) 1.0)
		(at item2 rooma)
		(at item3 rooma)
	)
	(:goal
			(and
				(at item10 roomb)
				(at item9 roomb)
				(at item8 roomd)
				(at item7 roomd)
				(at item6 roomd)
				(at item5 roomd)
				(at item4 roomc)
				(at item3 roomc)
				(at item2 roomc)
				(at item1 roomc)
			)
	)
)